"""Lineage of a catalog field: the seeded upstream hops and the derived tail.

The table is created by dbmate -the migration ``create_catalog_lineage``- and
this class only mirrors it. The response contracts reuse the catalog
vocabulary of US-008 -``SourceRef``, ``OwnerRef``, ``Validity``, ``Facets``-
instead of restating it: a second spelling of the same fact is the divergence
class the previous audit punished.

Four hops are stored and the fifth is composed. Persisting the terminal step
would duplicate columns ``catalog_field`` already owns, and the first
correction of a definition would leave the lineage saying one thing and the
dictionary another with nothing to detect it. That the step is derived is part
of the contract -``stored`` is ``False``- and not a hint the interface has to
guess.

Every value here is a stable code in ``snake_case``. The interface is bilingual
and keys its copy on these codes; a sentence in the body would exist in one
language only.
"""

from datetime import date, datetime
from enum import StrEnum
from typing import Final

from pydantic import BaseModel
from sqlmodel import Field, SQLModel

from app.models.catalog import Facets, OwnerRef, SourceRef, Validity


class LineageStage(StrEnum):
    """Hop of the journey. ``PRESENTACION`` is derived and never stored."""

    ORIGEN = "origen"
    EXTRACCION = "extraccion"
    TRANSFORMACION = "transformacion"
    CALIDAD = "calidad"
    PRESENTACION = "presentacion"


#: Transformation codes the seed may use, mirroring the ``CHECK`` of the
#: migration. The pair is compared row by row in the integration suite: a code
#: added on one side only would seed cleanly and reach the interface as a key
#: with no template, printed on screen as a dotted string in both languages.
LINEAGE_TRANSFORMATION_CODES: Final[tuple[str, ...]] = (
    "origin_capture",
    "batch_extract",
    "stream_extract",
    "type_normalization",
    "currency_conversion",
    "deduplication",
    "business_rule",
    "reconciliation",
    "quality_rule",
)

#: Code of the derived terminal step. Deliberately absent from the database
#: ``CHECK``: a constraint that admits a value nobody ever inserts is an
#: invitation to seed the derived hop "to complete the journey".
FIELD_PUBLISH_CODE: Final[str] = "field_publish"

#: System the terminal step names. It is the portal itself, because that hop
#: answers "this is the figure you are looking at" and no upstream system
#: publishes it.
PRESENTATION_SYSTEM_CODE: Final[str] = "KRS-Portal"
PRESENTATION_SYSTEM_NAME: Final[str] = "Karisma Data"

#: Steps every answer carries: the four seeded hops plus the derived one.
LINEAGE_STEP_COUNT: Final[int] = 5


class LineageErrorCode(StrEnum):
    """Stable codes this endpoint returns in ``detail.codigo``."""

    CAMPO_NO_ENCONTRADO = "campo_no_encontrado"


class ErrorLinaje(BaseModel):
    """Body of a typed failure. Code first, context after, prose never.

    Attributes:
        codigo: Stable identifier the interface keys its copy on.
        entry_id: Identifier that was asked for, echoed so the screen can name
            it in its error state without holding the request that failed.
    """

    codigo: LineageErrorCode
    entry_id: int

    def as_detail(self) -> dict[str, object]:
        """Render the body FastAPI puts under ``detail``.

        Returns:
            The populated fields, in the shape ``detail.codigo`` that US-025
            established and the composables of the portal already read.
        """
        return self.model_dump()


class CatalogLineageStep(SQLModel, table=True):
    """Mirror of ``catalog_lineage_step``: one stored hop of one source.

    The row hangs from the source and not from the field because the upstream
    stretch -capture, extraction, transformation and quality control- is the
    same work of the platform for every field of a source. One journey per
    field would be around twelve hundred rows generated by a rule, which is
    invented lineage dressed as data.

    Attributes:
        id: Primary key, ``BIGSERIAL`` on the database side.
        source_id: Foreign key to ``catalog_source``, ``ON DELETE CASCADE``.
        step_order: Position of the hop inside the journey, starting at one.
        stage: Stage code; never ``presentacion``, which is composed.
        system_code: System that performs the hop, as its operators name it.
        system_name: Readable name of that system. Data, not a label.
        transformation_code: Closed code; the visible prose lives in the
            ``lineage.transformation.*`` keys of the frontend catalogues.
        transformation_detail: Non translatable datum interpolated into that
            template: the name of a job, of a rule or of a control.
        owner_area: Area that answers for this hop, which is not necessarily
            the one that answers for the source.
        owner_name: Person that answers for this hop.
        effective_from: First day the hop is in force.
        effective_to: Last day it was in force; ``None`` means still in force.
        created_at: Row creation timestamp, ``now()`` on the database side.
    """

    __tablename__ = "catalog_lineage_step"

    id: int | None = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="catalog_source.id", index=True)
    step_order: int
    stage: str
    system_code: str
    system_name: str
    transformation_code: str
    transformation_detail: str
    owner_area: str
    owner_name: str
    effective_from: date
    effective_to: date | None = None
    created_at: datetime | None = None


class LineageStepOut(BaseModel):
    """One hop, as the overlay renders it. Codes only, never labels.

    Attributes:
        order: Position of the hop in the journey, starting at one.
        stage: Stage code.
        system_code: System that performs the hop.
        system_name: Readable name of that system.
        transformation_code: Closed code the interface turns into a sentence.
        transformation_detail: Datum interpolated into that sentence.
        owner: Who answers for this hop, already resolved.
        effective_from: First day the hop is in force.
        effective_to: Last day it was in force; ``None`` means still in force.
        is_current: Whether the hop is in force today, so the panel and the
            dates cannot disagree.
        stored: ``False`` on the terminal step, which is composed from
            ``catalog_field`` rather than stored. The overlay shows this to the
            reader; it is not an implementation hint.
    """

    order: int
    stage: LineageStage
    system_code: str
    system_name: str
    transformation_code: str
    transformation_detail: str
    owner: OwnerRef
    effective_from: date
    effective_to: date | None
    is_current: bool
    stored: bool


class FieldLineageResponse(BaseModel):
    """Payload of ``GET /api/catalog/{entry_id}/lineage``.

    Attributes:
        field_id: Identifier of the catalog entry the journey belongs to.
        physical_name: Column name in the system of record.
        business_name: Name a person uses for the field.
        source: Where the field lives, in the vocabulary of US-008.
        owner: Who answers for the field, steward first and source owner as
            the fallback, resolved on the server.
        validity: Effective period of the definition.
        facets: Filterable attributes, as codes.
        steps: The journey, in order: four stored hops and the derived one.
    """

    field_id: int
    physical_name: str
    business_name: str
    source: SourceRef
    owner: OwnerRef
    validity: Validity
    facets: Facets
    steps: list[LineageStepOut]
