import type { VueWrapper } from '@vue/test-utils'
import type { PayloadHistoricos, PuntoMensual } from '~/types/prediccion'

import { flushPromises, mount } from '@vue/test-utils'
import { defineComponent, ref, shallowRef } from 'vue'
import { afterEach, describe, expect, it, vi } from 'vitest'

import TableroPredicciones from '~/components/tablero/TableroPredicciones.vue'
import TarjetaPredictiva from '~/components/tablero/TarjetaPredictiva.vue'
import { esPayloadHistoricos } from '~/composables/usePrediccionesTablero'
import { METRICAS_PREDICCION } from '~/utils/metricasTablero'
import { MINIMO_PUNTOS, mesSiguiente, proyectarLineal } from '~/utils/proyeccion'
import publicado from '../public/datos/historicos-tablero.json'
import { type CodigoIdioma, clavesDe, crearI18nDePrueba } from './i18nDePrueba'

/**
 * US-026 - the predictive cards, their three levels and their four states.
 *
 * The components are mounted directly, with the real catalogues, and only the
 * transport is replaced. The `NuxtLink` double is declared here and not in
 * `test/i18nDePrueba.ts`: that helper is shared by several User Stories this
 * week and five duplicated lines cost less than a collision in a common file.
 */

const HISTORICO = publicado as unknown as PayloadHistoricos

const EnlaceStub = defineComponent({
  props: { to: { type: String, required: true } },
  template: '<a :href="to"><slot /></a>',
})

interface DesenlaceFetch {
  datos?: unknown
  error?: unknown
  estado?: 'idle' | 'pending' | 'success' | 'error'
}

/** Installs the `useFetch` double the composable loads the history through. */
function instalarFetch({ datos = null, error = null, estado = 'success' }: DesenlaceFetch) {
  const refresh = vi.fn(async () => undefined)
  vi.stubGlobal('useFetch', () => ({
    data: shallowRef(datos),
    error: ref(error),
    status: ref(estado),
    refresh,
  }))
  return { refresh }
}

/**
 * Mounts the section with the transport replaced.
 *
 * `adjuntar` puts the tree inside the document, which only the focus assertion
 * needs: `document.activeElement` stays on `<body>` for a detached tree, so
 * without it that test would measure the mount and not the behaviour.
 */
async function montarTablero(
  desenlace: DesenlaceFetch,
  idioma: CodigoIdioma = 'es',
  adjuntar = false,
) {
  const { refresh } = instalarFetch(desenlace)
  const wrapper = mount(TableroPredicciones, {
    attachTo: adjuntar ? document.body : undefined,
    global: {
      plugins: [crearI18nDePrueba(idioma)],
      components: { NuxtLink: EnlaceStub },
      stubs: { Icon: true },
    },
  })
  await flushPromises()
  return { wrapper, refresh }
}

/** The published payload with only the last `meses` months of every metric. */
function recortado(meses: number): PayloadHistoricos {
  return {
    ...HISTORICO,
    metricas: HISTORICO.metricas.map(metrica => ({
      ...metrica,
      puntos: metrica.puntos.slice(-meses),
    })),
  }
}

/**
 * Clicks needed to reach a revelation level, counted rather than promised.
 *
 * On every round it checks that the target level is NOT in the document, picks
 * the pending control with the lowest destination and presses it. It throws
 * past three presses, so a regression that buries a level shows up as a failure
 * and not as a slower test.
 */
async function abrirNivel(wrapper: VueWrapper, nivel: 2 | 3): Promise<number> {
  for (let pulsaciones = 0; pulsaciones <= 3; pulsaciones += 1) {
    if (wrapper.find(`[data-nivel="${nivel}"]`).exists()) {
      return pulsaciones
    }
    const pendientes = wrapper
      .findAll('[data-accion-revelacion]')
      .map(nodo => ({ nodo, destino: Number(nodo.attributes('data-nivel-destino')) }))
      .filter(
        ({ destino }) =>
          destino <= nivel && !wrapper.find(`[data-nivel="${destino}"]`).exists(),
      )
      .sort((izquierda, derecha) => izquierda.destino - derecha.destino)

    const siguiente = pendientes[0]
    if (siguiente === undefined) {
      throw new Error(`No hay ningun control que lleve al nivel ${nivel}`)
    }
    await siguiente.nodo.trigger('click')
    await flushPromises()
  }
  throw new Error(`El nivel ${nivel} no se alcanzo en tres pulsaciones`)
}

/** Monthly points of a perfect line, oldest first. */
function recta(puntos: number): PuntoMensual[] {
  let mes = '2024-07'
  return Array.from({ length: puntos }, (_, indice) => {
    const punto: PuntoMensual = { mes, valor: 2 * indice + 1 }
    mes = mesSiguiente(mes)
    return punto
  })
}

afterEach(() => {
  vi.unstubAllGlobals()
})

describe('el historico publicado', () => {
  it('cumple el contrato que la pantalla consume', () => {
    // The file is versioned and generated by a script nobody runs on every
    // commit: a regeneration that renamed a field would otherwise be found in
    // the middle of the demo.
    expect(esPayloadHistoricos(HISTORICO)).toBe(true)
    expect(HISTORICO.metricas.map(metrica => metrica.id)).toEqual(
      METRICAS_PREDICCION.map(metrica => metrica.id),
    )
    expect(HISTORICO.ventana).toEqual({ desde: '2024-07', hasta: '2026-06', meses: 24 })

    for (const metrica of HISTORICO.metricas) {
      const meses = metrica.puntos.map(punto => punto.mes)

      expect(metrica.puntos, metrica.id).toHaveLength(24)
      expect(meses.at(-1), metrica.id).toBe('2026-06')
      expect([...meses].sort(), metrica.id).toEqual(meses)
      expect(new Set(meses).size, metrica.id).toBe(24)
      for (const punto of metrica.puntos) {
        expect(Number.isFinite(punto.valor), `${metrica.id} ${punto.mes}`).toBe(true)
      }
    }
  })

  it('nombra agregaciones que existen en los dos catalogos', () => {
    // The aggregation travels as a translation key inside a file under
    // `public/`, which `test/contratos.spec.ts` does not scan: a typo there
    // would be printed as a dotted path inside the provenance panel.
    const claves = { es: new Set(clavesDe('es')), en: new Set(clavesDe('en')) }

    for (const metrica of HISTORICO.metricas) {
      expect(claves.es.has(metrica.claveAgregacion), metrica.claveAgregacion).toBe(true)
      expect(claves.en.has(metrica.claveAgregacion), metrica.claveAgregacion).toBe(true)
    }
  })
})

describe('la rejilla de tarjetas', () => {
  it('renderiza tres tarjetas en los cuatro estados', async () => {
    // The grid is built from METRICAS_PREDICCION and never from the response.
    // Iterating the payload would make a file with two metrics produce two
    // cards, and the row would reflow the moment the request settled.
    const desenlaces: DesenlaceFetch[] = [
      { estado: 'pending' },
      { datos: HISTORICO },
      { datos: recortado(4) },
      { error: new Error('sin red'), estado: 'error' },
    ]

    for (const desenlace of desenlaces) {
      const { wrapper } = await montarTablero(desenlace)

      expect(wrapper.findAll('[data-tarjeta]'), JSON.stringify(desenlace.estado)).toHaveLength(3)
    }
  })

  it('muestra la etiqueta de metodo de las tres tarjetas en los dos idiomas', async () => {
    // The criterion of honesty itself. A refactor that drops the label leaves
    // three figures with no method, which is an anonymous prediction.
    const espanol = await montarTablero({ datos: HISTORICO }, 'es')
    const ingles = await montarTablero({ datos: HISTORICO }, 'en')

    const leer = (wrapper: VueWrapper): string[] =>
      wrapper.findAll('[data-caja="metodo"]').map(nodo => nodo.text())

    const etiquetasEs = leer(espanol.wrapper)
    const etiquetasEn = leer(ingles.wrapper)

    expect(etiquetasEs).toHaveLength(3)
    for (const [indice, etiqueta] of etiquetasEs.entries()) {
      expect(etiqueta.length).toBeGreaterThan(0)
      expect(etiqueta).not.toBe(etiquetasEn[indice])
    }
  })

  it('cambia la etiqueta de metodo cuando cambia el calculo', () => {
    // The central assertion of the anti drift mechanism: it turns red the day
    // somebody writes the label as a fixed string again. The history is a
    // perfect line so that the coefficient reads the same in both mounts and
    // the only difference left in the sentence is the window.
    const historico = recta(24)
    const montar = (ventana: number) =>
      mount(TarjetaPredictiva, {
        props: {
          metrica: METRICAS_PREDICCION[0]!,
          proyeccion: proyectarLineal('cobertura-liquidez', historico, { ventana }),
          estado: 'listo' as const,
          abierta: false,
          idTitulo: 'titulo',
          idPanel: 'panel',
        },
        global: { plugins: [crearI18nDePrueba('es')], stubs: { Icon: true } },
      })

    const doce = montar(12).get('[data-caja="metodo"]').text()
    const seis = montar(6).get('[data-caja="metodo"]').text()

    expect(doce).toContain('12')
    expect(doce).not.toContain('6')
    expect(seis).toContain('6')
    expect(seis).not.toContain('12')
  })
})

describe('el esqueleto no mueve la maquetacion', () => {
  /** The `[data-caja]` boxes of the first card, with the class each declares. */
  function cajas(wrapper: VueWrapper): [string | undefined, string | undefined][] {
    return wrapper
      .findAll('[data-tarjeta]')[0]!
      .findAll('[data-caja]')
      .map(nodo => [nodo.attributes('data-caja'), nodo.attributes('class')])
  }

  it('declara las mismas cajas cargando y listo', async () => {
    // The cause of the shift, which is what happy-dom can measure: a filler
    // with a height of its own, or a paragraph that only exists once the data
    // is there, makes the card grow when the request settles.
    const cargando = await montarTablero({ estado: 'pending' })
    const listo = await montarTablero({ datos: HISTORICO })

    expect(cajas(cargando.wrapper)).toEqual(cajas(listo.wrapper))
  })

  it('no deja ninguna caja vacia en ninguno de los dos estados', async () => {
    // A filler written as an empty `<span>` collapses to zero height and the
    // card grows on arrival, which is the same defect through another door.
    for (const desenlace of [{ estado: 'pending' as const }, { datos: HISTORICO }]) {
      const { wrapper } = await montarTablero(desenlace)

      for (const caja of wrapper.findAll('[data-caja]')) {
        expect(caja.element.textContent?.length, caja.attributes('data-caja')).toBeGreaterThan(0)
      }
    }
  })

  it('mantiene la cifra en una sola linea y la etiqueta en dos', async () => {
    // A balance in millions that wraps to two lines, or an English method
    // sentence that spills into a third, stretches the card on arrival.
    const cargando = await montarTablero({ estado: 'pending' })
    const listo = await montarTablero({ datos: HISTORICO })

    for (const { wrapper } of [cargando, listo]) {
      expect(wrapper.get('[data-caja="valor"]').classes()).toContain('whitespace-nowrap')
      expect(wrapper.get('[data-caja="metodo"]').classes()).toContain('line-clamp-2')
    }
    expect(cargando.wrapper.get('[data-caja="metodo"]').findAll('span.block')).toHaveLength(2)
  })

  it('deja el boton de revelacion presente y deshabilitado mientras carga', async () => {
    // A button that appears with the data pushes the foot of the card down.
    const { wrapper } = await montarTablero({ estado: 'pending' })
    const botones = wrapper.findAll('[data-accion-revelacion]')

    expect(botones).toHaveLength(3)
    for (const boton of botones) {
      expect(boton.attributes('disabled')).toBeDefined()
    }
  })
})

describe('la revelacion progresiva', () => {
  it('alcanza el nivel 2 en un clic y el nivel 3 en dos', async () => {
    // With `toBe` and not `toBeLessThanOrEqual`: reaching a level in zero
    // clicks would mean the depth stopped being optional, which is the other
    // half of what progressive disclosure means.
    const primero = await montarTablero({ datos: HISTORICO })
    const segundo = await montarTablero({ datos: HISTORICO })

    expect(await abrirNivel(primero.wrapper, 2)).toBe(1)
    expect(await abrirNivel(segundo.wrapper, 3)).toBe(2)
  })

  it('mantiene los tres niveles distinguibles en el arbol', async () => {
    // Merging the table into the panel and stopping at two levels without
    // declaring the valve would be silent scope loss.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    await abrirNivel(wrapper, 3)

    expect(wrapper.findAll('[data-nivel="1"]')).toHaveLength(3)
    expect(wrapper.findAll('[data-nivel="2"]')).toHaveLength(1)
    expect(wrapper.findAll('[data-nivel="3"]')).toHaveLength(1)
  })

  it('opera los controles con teclado y anuncia su estado', async () => {
    // A `<div @click>` would pass the click count and leave the keyboard and
    // the screen reader out.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    await abrirNivel(wrapper, 3)

    const controles = wrapper.findAll('[data-accion-revelacion]')

    expect(controles.length).toBeGreaterThan(3)
    for (const control of controles) {
      expect(control.element.tagName).toBe('BUTTON')
      expect(control.attributes('aria-expanded')).toBeDefined()
      expect(control.attributes('aria-controls')).toBeDefined()
    }
  })

  it('cierra la tarjeta anterior al abrir otra', async () => {
    // Three open panels turn the screen into a page that grows downwards with
    // no way back to the summary.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    const botones = wrapper.findAll('[data-accion-revelacion]')

    await botones[0]!.trigger('click')
    await flushPromises()
    await wrapper.findAll('[data-accion-revelacion]')[1]!.trigger('click')
    await flushPromises()

    expect(wrapper.findAll('[data-nivel="2"]')).toHaveLength(1)
    expect(wrapper.get('[data-tarjeta="saldo-disponible"] [data-accion-revelacion]').attributes('aria-expanded')).toBe('true')
  })

  it('vuelve a cerrarse y devuelve el foco al boton que lo abrio', async () => {
    // What is revealed has to be closable, and closing with the keyboard has
    // to leave the reader where they were and not at the top of the document.
    const { wrapper } = await montarTablero({ datos: HISTORICO }, 'es', true)
    await abrirNivel(wrapper, 2)

    await wrapper.get('[data-nivel="2"]').trigger('keydown.esc')
    await flushPromises()

    expect(wrapper.find('[data-nivel="2"]').exists()).toBe(false)
    expect(document.activeElement).toBe(
      wrapper.get('[data-tarjeta="cobertura-liquidez"] [data-accion-revelacion]').element,
    )
    wrapper.unmount()
  })
})

describe('el nivel 2 dice de donde sale la cifra', () => {
  it('renderiza el descargo de que no hay aprendizaje automatico', async () => {
    // Dropping it for space leaves a screen that suggests a trained model,
    // which is exactly what the acceptance criterion forbids.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    const i18n = crearI18nDePrueba('es')
    await abrirNivel(wrapper, 2)

    expect(wrapper.get('[data-descargo]').text()).toBe(
      i18n.global.t('forecast.method.disclaimer'),
    )
  })

  it('nombra la columna fisica y la agregacion', async () => {
    // A figure with no lineage is the moment the journey map of A2 marks as
    // the one where the reader stops trusting the number.
    //
    // The expected copy is the balance weighted mean and no longer the one
    // weighted by position count: `ratio_lcr` arrives from US-006 already
    // weighted by balance, so that was the wrong weight and the sentence on
    // screen described an aggregation the card did not perform.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    const i18n = crearI18nDePrueba('es')
    await abrirNivel(wrapper, 2)

    const procedencia = wrapper.get('[data-procedencia]').text()

    expect(procedencia).toContain('ratio_lcr')
    expect(procedencia).toContain(i18n.global.t('forecast.aggregation.balanceWeightedMean'))
  })

  it('da nombre y resumen accesibles a la grafica', async () => {
    // Leaving the textual summary in Spanish only is what the bilingual
    // decision of 10-ago forbids explicitly, and a canvas with no summary does
    // not exist at all for a screen reader.
    const espanol = await montarTablero({ datos: HISTORICO }, 'es')
    const ingles = await montarTablero({ datos: HISTORICO }, 'en')
    await abrirNivel(espanol.wrapper, 2)
    await abrirNivel(ingles.wrapper, 2)

    const svg = espanol.wrapper.get('[data-grafica="proyeccion"]')
    const titulo = espanol.wrapper.get('[data-grafica="proyeccion"] title')
    const resumen = espanol.wrapper.get('[data-grafica="proyeccion"] desc')

    expect(svg.attributes('role')).toBe('img')
    expect(svg.attributes('aria-labelledby')).toBe(
      `${titulo.attributes('id')} ${resumen.attributes('id')}`,
    )
    expect(titulo.text().length).toBeGreaterThan(0)
    expect(resumen.text().length).toBeGreaterThan(0)
    expect(resumen.text()).not.toBe(
      ingles.wrapper.get('[data-grafica="proyeccion"] desc').text(),
    )
  })

  it('distingue el tramo proyectado sin recurrir al color', async () => {
    // Telling the two segments apart by colour alone leaves out the reader
    // profiles of A1 with reduced colour vision.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    await abrirNivel(wrapper, 2)

    const observado = wrapper.get('[data-tramo="observado"]')
    const proyectado = wrapper.get('[data-tramo="proyectado"]')

    expect(observado.attributes('stroke-dasharray')).toBeUndefined()
    expect(proyectado.attributes('stroke-dasharray')).toBeDefined()
    expect(proyectado.attributes('class')).toBe(observado.attributes('class'))
    expect(wrapper.get('[data-marcador="proyectado"]').attributes('fill')).toBe('none')
    expect(wrapper.findAll('[data-leyenda] li')).toHaveLength(2)
  })
})

describe('el nivel 3', () => {
  it('es una tabla con caption y encabezados de columna', async () => {
    // A grid of `<div>` cannot be walked row by row with a screen reader, and
    // the chart above carries no structure at all.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    await abrirNivel(wrapper, 3)

    const tabla = wrapper.get('[data-nivel="3"] table')

    expect(tabla.get('caption').text().length).toBeGreaterThan(0)
    expect(tabla.findAll('th[scope="col"]')).toHaveLength(3)
    expect(tabla.findAll('tbody tr')).toHaveLength(25)
    expect(tabla.findAll('[data-fila="proyectada"]')).toHaveLength(1)
  })

  it('lleva al explorador con el termino de la metrica', async () => {
    // A link with no term lands on an empty explorer and cuts the demo path
    // right where the reader was going deeper.
    const { wrapper } = await montarTablero({ datos: HISTORICO })
    await abrirNivel(wrapper, 3)

    expect(wrapper.get('[data-accion="explorar"]').attributes('href')).toBe(
      '/exploracion?q=ratio_lcr',
    )
  })
})

describe('los estados que no son el feliz', () => {
  it('no inventa un numero cuando no hay historia suficiente', async () => {
    // Painting a zero or a dash as if it were a measurement is the dishonesty
    // the empty state exists to avoid.
    const { wrapper } = await montarTablero({ datos: recortado(4) })
    const i18n = crearI18nDePrueba('es')

    expect(wrapper.findAll('[data-tarjeta][data-estado="vacio"]')).toHaveLength(3)
    for (const caja of wrapper.findAll('[data-caja="valor"]')) {
      expect(caja.text()).not.toMatch(/\d/)
    }
    for (const caja of wrapper.findAll('[data-caja="metodo"]')) {
      expect(caja.text()).toBe(
        i18n.global.t('forecast.state.emptyHint', { minimum: MINIMO_PUNTOS }),
      )
    }
  })

  it('ofrece reintentar en el error y vuelve a pedir el dato', async () => {
    // A mute failure, or a retry that does not retry, both leave the reader
    // with nothing to do but reload the whole screen.
    const { wrapper, refresh } = await montarTablero({
      error: new Error('sin red'),
      estado: 'error',
    })

    expect(wrapper.find('[data-error]').exists()).toBe(true)
    await wrapper.get('[data-reintentar]').trigger('click')

    expect(refresh).toHaveBeenCalledTimes(1)
  })

  it('no revienta con un payload malformado y deja las tarjetas sin cifra', async () => {
    // A half regenerated JSON would otherwise be a blank screen in the middle
    // of the demo, because `.map` over a string throws during render.
    const { wrapper } = await montarTablero({ datos: { metricas: 'no soy un arreglo' } })

    expect(wrapper.findAll('[data-tarjeta][data-estado="error"]')).toHaveLength(3)
    for (const caja of wrapper.findAll('[data-caja="valor"]')) {
      expect(caja.text()).not.toMatch(/\d/)
    }
  })

  it('no ofrece reintentar cuando el error no es recuperable', async () => {
    // The retry belongs to the failed request alone: offering it over an empty
    // history teaches the reader to insist against a door that will not open.
    const { wrapper } = await montarTablero({ datos: recortado(4) })

    expect(wrapper.find('[data-reintentar]').exists()).toBe(false)
  })
})

describe('nada de lo que se muestra depende del reloj', () => {
  it('renderiza lo mismo en dos instantes distintos', async () => {
    // A screenshot taken on Saturday for the A4 document has to match the one
    // taken on Wednesday: every date on this screen comes from the payload.
    vi.useFakeTimers({ toFake: ['Date'] })
    try {
      vi.setSystemTime(new Date('2020-01-01T00:00:00Z'))
      const primero = await montarTablero({ datos: HISTORICO })
      const antes = primero.wrapper.html()

      vi.setSystemTime(new Date('2031-06-15T23:59:00Z'))
      const segundo = await montarTablero({ datos: HISTORICO })

      expect(segundo.wrapper.html()).toBe(antes)
    }
    finally {
      vi.useRealTimers()
    }
  })
})
