"""Figures for deliverable A3 (competitive analysis and information architecture).

Note: a3_dendrograma.png, a3_matriz_similitud.png and a3_disputa.png are NOT
produced here. They are generated by analisis_a3.py from the real card-sorting
runs stored in datos/a3_sorts/. This script must never overwrite them.
"""

import os
import textwrap

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

# Configuración de colores institucionales
COLOR_NAVY = '#1F4D78'
COLOR_BLUE = '#2563EB'
COLOR_SKY = '#3B82F6'
COLOR_AMBER = '#F97316'
COLOR_MUTED = '#64748B'

# Tonos derivados (rellenos claros, legibles en blanco y negro)
COLOR_SKY_SOFT = '#DBEAFE'
COLOR_AMBER_SOFT = '#FDE6CF'
COLOR_AMBER_DARK = '#9A3412'
COLOR_PAPER = '#F8FAFC'


def draw_box(ax, x, y, w, h, facecolor, edgecolor=COLOR_NAVY, lw=1.4,
             zorder=5):
    """Draw a plain rectangle used as a node of the diagrams."""
    patch = Rectangle((x, y), w, h, facecolor=facecolor, edgecolor=edgecolor,
                      lw=lw, zorder=zorder)
    ax.add_patch(patch)
    return patch


def draw_change_band(ax, x, y, w, h, zorder=7):
    """Draw the solid amber band that flags a node changed after the test.

    A solid band survives a black and white printout (it turns into a dark
    strip) without laying a texture behind the label, so the text stays
    readable.
    """
    ax.add_patch(Rectangle((x, y), w, h, facecolor=COLOR_AMBER,
                           edgecolor=COLOR_AMBER, lw=0.8, zorder=zorder))


def draw_elbow(ax, x0, y0, x1, y1, color=COLOR_MUTED, lw=1.2, ls='-',
               zorder=2):
    """Draw an orthogonal connector: vertical drop, then horizontal run."""
    ax.plot([x0, x0], [y0, y1], color=color, lw=lw, ls=ls, zorder=zorder,
            solid_capstyle='butt')
    ax.plot([x0, x1], [y1, y1], color=color, lw=lw, ls=ls, zorder=zorder,
            solid_capstyle='butt')


def generar_matriz_competitiva():
    """Genera un gráfico de gradiente de características vs costo/esfuerzo"""
    fig, ax = plt.subplots(figsize=(10, 6))

    # Datos simulados de competidores
    competidores = ['Karisma Data', 'Bloomberg Terminal',
                    'Herramientas BI (Power BI, Pyramid)',
                    'Bases Aisladas / Excel', 'Silos Departamentales']
    x_cost = [4, 9, 5, 2, 3]   # Costo/Esfuerzo
    y_feat = [9, 10, 7, 3, 4]  # Características para la Institución
    sizes = [800, 500, 500, 400, 400]
    colors = [COLOR_AMBER, COLOR_NAVY, COLOR_SKY, COLOR_MUTED, COLOR_MUTED]

    ax.scatter(x_cost, y_feat, s=sizes, c=colors, alpha=0.8, edgecolors='w',
               linewidth=2)

    # Etiquetas
    for i, txt in enumerate(competidores):
        ax.annotate(txt, (x_cost[i], y_feat[i]), xytext=(0, -15),
                    textcoords='offset points', ha='center', va='top',
                    fontweight='bold' if txt == 'Karisma Data' else 'normal',
                    color=COLOR_NAVY)

    ax.set_title('Gradiente de Postura Competitiva (Institucional)',
                 fontsize=16, fontweight='bold', color=COLOR_NAVY, pad=20)
    ax.set_xlabel('Costo y Esfuerzo de Implementación', fontsize=12,
                  color=COLOR_NAVY)
    ax.set_ylabel('Funcionalidad Específica (Datos Macroeconómicos/Silos)',
                  fontsize=12, color=COLOR_NAVY)

    ax.set_xlim(0, 10)
    ax.set_ylim(0, 11)

    ax.grid(True, linestyle='--', alpha=0.5, color=COLOR_MUTED)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color(COLOR_NAVY)
    ax.spines['bottom'].set_color(COLOR_NAVY)

    plt.tight_layout()
    plt.savefig('figuras/a3_matriz_competitiva.png', dpi=300,
                bbox_inches='tight')
    plt.close()


# --- Revised architecture (post tree-testing) -------------------------------
# changed=True marks the nodes modified after the tree test; they are drawn in
# amber with a solid side band so the change survives a grayscale printout.
REVISED_TREE = [
    {
        'titulo': '1. Inicio',
        'changed': False,
        'hijos': [
            {'titulo': 'Buscador unificado', 'detalle': '', 'changed': False},
            {'titulo': 'Búsquedas recientes', 'detalle': '', 'changed': False},
            {'titulo': 'Favoritos', 'detalle': '', 'changed': False},
            {'titulo': 'Mis alertas', 'detalle': '', 'changed': False},
            {'titulo': 'Mi perfil', 'detalle': '', 'changed': False},
        ],
    },
    {
        'titulo': '2. Exploración y extracción',
        'changed': False,
        'hijos': [
            {'titulo': '2.1 Catálogo temático',
             'detalle': 'Crédito, liquidez, derivados, captación, mercado de '
                        'dinero, acciones',
             'changed': False},
            {'titulo': '2.2 Consulta y filtros',
             'detalle': 'Buscador facetado, filtros avanzados, vista previa, '
                        'compartir consulta',
             'changed': False},
            {'titulo': '2.3 Exportaciones',
             'detalle': 'Exportación CSV/Excel, historial de exportaciones',
             'changed': False},
            {'titulo': '2.4 Tableros e indicadores',
             'detalle': 'Tablero ejecutivo, indicadores de riesgo, señales de '
                        'riesgo',
             'changed': True},
        ],
    },
    {
        'titulo': '3. Gobierno del dato',
        'changed': True,
        'hijos': [
            {'titulo': '3.1 Diccionario y metadatos',
             'detalle': 'Diccionario de datos, metadatos, reglas de negocio',
             'changed': False},
            {'titulo': '3.2 Linaje y calidad',
             'detalle': 'Linaje, calidad de datos, monitoreo de cargas',
             'changed': False},
            {'titulo': '3.3 Catálogo de fuentes',
             'detalle': 'Con faceta transversal hacia Exploración',
             'changed': False},
        ],
    },
    {
        'titulo': '4. Administración',
        'changed': False,
        'hijos': [
            {'titulo': '4.1 Usuarios, roles y permisos',
             'detalle': 'Usuarios y roles, permisos',
             'changed': False},
            {'titulo': '4.2 Solicitudes y aprobaciones',
             'detalle': 'Solicitar acceso, estado de solicitudes, flujos de '
                        'aprobación',
             'changed': False},
            {'titulo': '4.3 Bitácora de accesos',
             'detalle': 'Con acceso cruzado desde Gobierno del dato',
             'changed': True},
            {'titulo': '4.4 Integraciones',
             'detalle': 'Credenciales API, consumo por API, conectores de '
                        'fuentes',
             'changed': False},
        ],
    },
]


def generar_mapa_navegacion():
    """Draw the revised site map as a left to right tree (portrait friendly)."""
    fig, ax = plt.subplots(figsize=(8.2, 10.2))

    # Geometría de las tres columnas: raíz, módulos, segundo nivel.
    root_x, root_w = 1.0, 16.0
    mod_x, mod_w = 19.5, 23.0
    root_bus_x = 17.2
    child_bus_x = 44.5
    child_x, child_w = 48.5, 50.5
    cross_x = 46.5

    box_h, gap, group_gap = 4.0, 0.85, 1.8
    y_cursor = 98.0

    mod_centers = []
    child_centers = {}

    # Primera pasada: reservar el espacio vertical de cada módulo.
    for modulo in REVISED_TREE:
        centros = []
        for hijo in modulo['hijos']:
            y0 = y_cursor - box_h
            centros.append(y0 + box_h / 2)
            y_cursor = y0 - gap
        child_centers[modulo['titulo']] = centros
        mod_centers.append((centros[0] + centros[-1]) / 2)
        y_cursor -= group_gap

    # Raíz
    root_cy = (mod_centers[0] + mod_centers[-1]) / 2
    root_h = 11.0
    draw_box(ax, root_x, root_cy - root_h / 2, root_w, root_h, COLOR_NAVY,
             COLOR_NAVY, lw=1.8)
    ax.text(root_x + root_w / 2, root_cy,
            'Karisma Data\n\nPortal de datos\nfinancieros',
            ha='center', va='center', color='white', fontsize=8.5,
            fontweight='bold', zorder=10, linespacing=1.4)
    ax.plot([root_x + root_w, root_bus_x], [root_cy, root_cy],
            color=COLOR_MUTED, lw=1.2, zorder=2)
    ax.plot([root_bus_x, root_bus_x], [mod_centers[0], mod_centers[-1]],
            color=COLOR_MUTED, lw=1.2, zorder=2)

    bitacora_cy = None
    mod3_bottom = None

    for modulo, mod_cy in zip(REVISED_TREE, mod_centers):
        centros = child_centers[modulo['titulo']]
        changed = modulo['changed']
        mod_h = min(10.0, centros[0] - centros[-1] + box_h)
        mod_y = mod_cy - mod_h / 2

        ax.plot([root_bus_x, mod_x], [mod_cy, mod_cy], color=COLOR_MUTED,
                lw=1.2, zorder=2)
        draw_box(ax, mod_x, mod_y, mod_w, mod_h,
                 COLOR_AMBER if changed else COLOR_NAVY,
                 COLOR_AMBER_DARK if changed else COLOR_NAVY,
                 lw=2.4 if changed else 1.4)
        ax.text(mod_x + mod_w / 2, mod_cy, textwrap.fill(modulo['titulo'], 15),
                ha='center', va='center', color='white', fontsize=10.5,
                fontweight='bold', zorder=10, linespacing=1.4)
        if modulo['titulo'].startswith('3.'):
            mod3_bottom = mod_y

        # Bus vertical del módulo hacia sus hijos
        ax.plot([mod_x + mod_w, child_bus_x], [mod_cy, mod_cy],
                color=COLOR_MUTED, lw=1.2, zorder=2)
        ax.plot([child_bus_x, child_bus_x], [centros[0], centros[-1]],
                color=COLOR_MUTED, lw=1.2, zorder=2)

        for hijo, cy in zip(modulo['hijos'], centros):
            hijo_changed = hijo['changed']
            y0 = cy - box_h / 2
            ax.plot([child_bus_x, child_x], [cy, cy], color=COLOR_MUTED,
                    lw=1.2, zorder=2)
            draw_box(ax, child_x, y0, child_w, box_h,
                     COLOR_AMBER_SOFT if hijo_changed else COLOR_SKY_SOFT,
                     COLOR_AMBER if hijo_changed else COLOR_NAVY,
                     lw=2.2 if hijo_changed else 1.2)
            texto_x = child_x + 1.4
            if hijo_changed:
                draw_change_band(ax, child_x, y0, 1.5, box_h)
                texto_x = child_x + 2.6
            if hijo['detalle']:
                ax.text(texto_x, y0 + box_h - 0.8,
                        hijo['titulo'], ha='left', va='top', color=COLOR_NAVY,
                        fontsize=9, fontweight='bold', zorder=10)
                ax.text(texto_x, y0 + box_h - 2.1,
                        textwrap.fill(hijo['detalle'], 76), ha='left',
                        va='top', color=COLOR_MUTED, fontsize=7,
                        zorder=10, linespacing=1.35)
            else:
                ax.text(texto_x, cy, hijo['titulo'], ha='left', va='center',
                        color=COLOR_NAVY, fontsize=9, fontweight='bold',
                        zorder=10)
            if hijo['titulo'].startswith('4.3'):
                bitacora_cy = cy

    # Acceso cruzado: Gobierno del dato -> 4.3 Bitácora de accesos
    ax.plot([mod_x + mod_w, cross_x], [mod3_bottom, mod3_bottom],
            color=COLOR_AMBER, lw=1.8, ls=(0, (3.5, 2.5)), zorder=8)
    ax.plot([cross_x, cross_x], [mod3_bottom, bitacora_cy], color=COLOR_AMBER,
            lw=1.8, ls=(0, (3.5, 2.5)), zorder=8)
    ax.annotate('', xy=(child_x, bitacora_cy), xytext=(cross_x, bitacora_cy),
                arrowprops=dict(arrowstyle='-|>', color=COLOR_AMBER, lw=1.8,
                                shrinkA=0, shrinkB=0), zorder=8)
    ax.text(cross_x - 0.8, (mod3_bottom + bitacora_cy) / 2, 'acceso cruzado',
            rotation=90, ha='center', va='center', color=COLOR_AMBER_DARK,
            fontsize=7.5, fontweight='bold', zorder=10,
            bbox=dict(boxstyle='square,pad=0.15', facecolor='white',
                      edgecolor='none'))

    # Leyenda
    leg_x, leg_y, leg_w, leg_h = 1.0, 1.0, 98.0, 12.0
    draw_box(ax, leg_x, leg_y, leg_w, leg_h, COLOR_PAPER, COLOR_MUTED, lw=1.0,
             zorder=3)
    sw_y = leg_y + leg_h - 3.4
    draw_box(ax, leg_x + 2.0, sw_y, 6.0, 2.4, COLOR_AMBER_SOFT, COLOR_AMBER,
             lw=2.2, zorder=6)
    draw_change_band(ax, leg_x + 2.0, sw_y, 1.1, 2.4)
    ax.text(leg_x + 9.5, sw_y + 1.2,
            'El ámbar marca los cambios aplicados tras la prueba de árbol.',
            ha='left', va='center', color=COLOR_AMBER_DARK, fontsize=9,
            fontweight='bold', zorder=10)
    ax.text(leg_x + 2.0, leg_y + leg_h - 4.6,
            'Cambio 1: los tableros e indicadores de riesgo pasaron de '
            'Gobierno a Exploración (la tarea 3 acertó 1 de 8).\n'
            'Cambio 2: la categoría 3 se renombró Gobierno del dato al salir '
            'los tableros.\n'
            'Cambio 3: la bitácora de accesos permanece en Administración y '
            'recibe un acceso cruzado desde Gobierno\ndel dato (los 8 '
            'evaluadores titubearon en la tarea 4).',
            ha='left', va='top', color=COLOR_NAVY, fontsize=7.5, zorder=10,
            linespacing=1.7)

    ax.set_title('Mapa de navegación de Karisma Data\n'
                 '(versión revisada tras la prueba de árbol)',
                 fontsize=13, fontweight='bold', color=COLOR_NAVY, pad=12)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.axis('off')

    plt.tight_layout()
    plt.savefig('figuras/a3_mapa_sitio.png', dpi=300, bbox_inches='tight')
    plt.close()


# Facets asked as multiple placements by three or more evaluators (out of 8).
# 0 = Inicio, 1 = Exploración y extracción, 2 = Gobierno del dato,
# 3 = Administración. "principal" is the home node in the revised tree and
# "cruces" the categories reached through multiple labelling.
FACETAS = [
    ('Consumo por API', 6, 3, [1]),
    ('Calidad de datos', 6, 2, [1]),
    ('Vista previa', 4, 1, [2]),
    ('Catálogo de fuentes', 4, 2, [1]),
    ('Mis alertas', 4, 0, [1]),
    ('Credenciales API', 4, 3, [0]),
    ('Monitoreo de cargas', 3, 2, [1]),
    ('Permisos', 3, 3, [2]),
    ('Historial de exportaciones', 3, 1, [3]),
]

NECESIDADES = [
    'Consulta inmediata\ny retorno al trabajo',
    'Análisis, cruce\ny extracción',
    'Definición, linaje\ny calidad del dato',
    'Accesos, permisos\ne integraciones',
]

TAREAS = [
    'Entrar, buscar\ny retomar',
    'Explorar, consultar,\nexportar y vigilar',
    'Definir y respaldar\nel dato',
    'Autorizar, auditar\ny conectar',
]


def generar_arquitectura_informacion(
        audience_label='evaluadores prototipo',
        output_name='a3_arquitectura_informacion.png'):
    """Draw the revised information architecture and its cross-cutting facets."""
    fig, ax = plt.subplots(figsize=(8.0, 10.6))

    label_w = 25.0
    col_w = (100.0 - label_w) / 4.0
    centers = [label_w + col_w / 2 + i * col_w for i in range(4)]
    box_w = col_w - 2.0

    def band_label(text, y):
        ax.text(0.5, y, text, ha='left', va='center', color=COLOR_MUTED,
                fontsize=7.5, fontweight='bold', linespacing=1.6)

    # Fila 1: necesidades por perfil
    y_need, h_need = 90.0, 6.5
    band_label('NECESIDADES\nPOR PERFIL', y_need + h_need / 2)
    for cx, texto in zip(centers, NECESIDADES):
        draw_box(ax, cx - box_w / 2, y_need, box_w, h_need, COLOR_NAVY,
                 COLOR_NAVY, lw=1.4)
        ax.text(cx, y_need + h_need / 2, texto, ha='center', va='center',
                color='white', fontsize=7.5, fontweight='bold', zorder=10,
                linespacing=1.4)

    # Fila 2: tareas
    y_task, h_task = 81.0, 6.0
    band_label('TAREAS', y_task + h_task / 2)
    for cx, texto in zip(centers, TAREAS):
        ax.plot([cx, cx], [y_need, y_task + h_task], color=COLOR_MUTED,
                lw=1.1, zorder=2)
        draw_box(ax, cx - box_w / 2, y_task, box_w, h_task, COLOR_SKY_SOFT,
                 COLOR_NAVY, lw=1.1)
        ax.text(cx, y_task + h_task / 2, texto, ha='center', va='center',
                color=COLOR_NAVY, fontsize=7.5, fontweight='bold', zorder=10,
                linespacing=1.4)

    # Fila 3: categorías de la arquitectura revisada
    y_cat, h_cat = 73.0, 5.0
    band_label('CATEGORÍAS\n(ARQUITECTURA\nREVISADA)', y_cat + h_cat / 2)
    for cx, modulo in zip(centers, REVISED_TREE):
        ax.plot([cx, cx], [y_task, y_cat + h_cat], color=COLOR_MUTED, lw=1.1,
                zorder=2)
        changed = modulo['changed']
        draw_box(ax, cx - box_w / 2, y_cat, box_w, h_cat,
                 COLOR_AMBER if changed else COLOR_SKY,
                 COLOR_AMBER_DARK if changed else COLOR_NAVY,
                 lw=2.0 if changed else 1.1)
        ax.text(cx, y_cat + h_cat / 2, textwrap.fill(modulo['titulo'], 16),
                ha='center', va='center', color='white', fontsize=8,
                fontweight='bold', zorder=10, linespacing=1.4)

    # Fila 4: objetos de información
    y_obj_top = 70.0
    obj_h, obj_gap = 4.0, 1.0
    band_label('OBJETOS DE\nINFORMACIÓN', y_obj_top - 2.4 * (obj_h + obj_gap))
    for cx, modulo in zip(centers, REVISED_TREE):
        y_top = y_obj_top
        for hijo in modulo['hijos']:
            y0 = y_top - obj_h
            changed = hijo['changed']
            ax.plot([cx, cx], [y0 + obj_h, y_top], color=COLOR_MUTED, lw=1.0,
                    ls=':', zorder=2)
            draw_box(ax, cx - box_w / 2, y0, box_w, obj_h,
                     COLOR_AMBER_SOFT if changed else 'white',
                     COLOR_AMBER if changed else COLOR_MUTED,
                     lw=2.0 if changed else 1.0)
            if changed:
                draw_change_band(ax, cx - box_w / 2, y0, 1.3, obj_h)
            ax.text(cx + (0.7 if changed else 0.0), y0 + obj_h / 2,
                    textwrap.fill(hijo['titulo'], 20), ha='center',
                    va='center', color=COLOR_NAVY, fontsize=7, zorder=10,
                    linespacing=1.4)
            y_top = y0 - obj_gap

    # Fila 5: facetas transversales de etiquetado múltiple
    y_band = 41.5
    ax.plot([0.5, 99.5], [y_band + 2.6, y_band + 2.6], color=COLOR_AMBER,
            lw=1.2, ls=(0, (5, 4)), zorder=2)
    ax.text(0.5, y_band, 'FACETAS TRANSVERSALES (ETIQUETADO MÚLTIPLE)',
            ha='left', va='center', color=COLOR_AMBER_DARK, fontsize=8.5,
            fontweight='bold')
    ax.text(0.5, y_band - 2.4,
            f'Tarjetas que los {audience_label} pidieron colocar en dos o '
            'más grupos a la vez: cada una vive en un nodo principal\ny se '
            'alcanza además desde otra categoría, de modo que cruza la '
            'jerarquía en lugar de duplicarse. El relleno ámbar\nde arriba '
            'marca los nodos modificados tras la prueba de árbol.',
            ha='left', va='top', color=COLOR_MUTED, fontsize=7,
            linespacing=1.7)

    y_head = 31.0
    for cx, modulo in zip(centers, REVISED_TREE):
        ax.text(cx, y_head, textwrap.fill(modulo['titulo'], 14), ha='center',
                va='center', color=COLOR_NAVY, fontsize=7.5,
                fontweight='bold', linespacing=1.4)
    ax.text(0.5, y_head, 'Faceta', ha='left', va='center', color=COLOR_NAVY,
            fontsize=7.5, fontweight='bold')
    ax.text(label_w - 1.0, y_head, 'Duplicados', ha='right', va='center',
            color=COLOR_NAVY, fontsize=7.5, fontweight='bold')
    ax.plot([0.5, 99.5], [y_head - 2.6, y_head - 2.6], color=COLOR_NAVY,
            lw=1.1, zorder=2)

    y_row = y_head - 5.0
    for nombre, conteo, principal, cruces in FACETAS:
        ax.plot([0.5, 99.5], [y_row - 1.25, y_row - 1.25], color='#E2E8F0',
                lw=0.8, zorder=1)
        ax.text(0.5, y_row, nombre, ha='left', va='center', color=COLOR_NAVY,
                fontsize=7)
        ax.text(label_w - 1.0, y_row, '%d de 8' % conteo, ha='right',
                va='center', color=COLOR_MUTED, fontsize=7)
        for idx, cx in enumerate(centers):
            if idx == principal:
                ax.plot([cx], [y_row], marker='s', markersize=7,
                        color=COLOR_NAVY, zorder=6)
            elif idx in cruces:
                ax.plot([cx], [y_row], marker='o', markersize=7,
                        markerfacecolor='white', markeredgecolor=COLOR_AMBER,
                        markeredgewidth=2.0, zorder=6)
        y_row -= 2.5

    # Leyenda de marcadores
    y_leg = y_row - 0.6
    ax.plot([1.5], [y_leg], marker='s', markersize=7, color=COLOR_NAVY,
            zorder=6)
    ax.text(3.5, y_leg, 'Ubicación principal en la arquitectura revisada',
            ha='left', va='center', color=COLOR_NAVY, fontsize=7)
    ax.plot([52.0], [y_leg], marker='o', markersize=7, markerfacecolor='white',
            markeredgecolor=COLOR_AMBER, markeredgewidth=2.0, zorder=6)
    ax.text(54.0, y_leg, 'Acceso cruzado por etiquetado múltiple',
            ha='left', va='center', color=COLOR_AMBER_DARK, fontsize=7)

    ax.set_title('Arquitectura de información de Karisma Data\n'
                 '(versión revisada tras la prueba de árbol)',
                 fontsize=13, fontweight='bold', color=COLOR_NAVY, pad=12)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.axis('off')

    plt.tight_layout()
    plt.savefig(f'figuras/{output_name}', dpi=300,
                bbox_inches='tight')
    plt.close()


if __name__ == '__main__':
    # Ensure directory exists
    os.makedirs('figuras', exist_ok=True)

    generar_matriz_competitiva()
    generar_mapa_navegacion()
    generar_arquitectura_informacion()
    print('Figuras A3 generadas: a3_matriz_competitiva.png, '
          'a3_mapa_sitio.png, a3_arquitectura_informacion.png')
