"""Emit the style guide of the course report from its single source of truth.

Reads every colour declaration of ``docs/entregables/estilo/uxdoc.sty`` and
emits the LaTeX plates of the guide plus a machine readable manifest::

    uxdoc.sty
        -> docs/entregables/estilo/a4_tokens.tex   (plates of the guide)
        -> docs/entregables/datos/a4_tokens.json   (manifest)

Nothing under ``frontend/`` belongs here. The portal declares its own system in
``design/sistema.py`` and publishes it through ``design/emitir.py``; deriving
the screen from a palette measured for ink is forbidden by ADR-002. Until the
14th of August 2026 this module also wrote ``main.css`` and
``tokens.generated.ts``, so every ``make tokens`` swapped the design system of
the portal for the palette of the report.

This module holds no colour literal: every value comes from the stylesheet, so
"no colour written by hand" is a check and not a convention. The regular
expressions below parse the TeX declarations, which carry no leading hash mark
either.

Usage::

    make tokens                                   # write both outputs
    python generar_tokens_a4.py --verificar       # walk without writing
    python generar_tokens_a4.py --destino DIR     # mirror the tree under DIR
"""

from __future__ import annotations

import argparse
import json
import re
from collections.abc import Sequence
from dataclasses import dataclass
from itertools import pairwise
from pathlib import Path
from typing import Any, Final, Literal

import structlog

LOG: Final[structlog.stdlib.BoundLogger] = structlog.get_logger()

VERSION_GUIA: Final[str] = "v1.0"
FECHA_GUIA: Final[str] = "2026-08-16"
FECHA_GUIA_LARGA: Final[str] = "16 de agosto de 2026"

# The hash mark lives here and nowhere else: a colour literal would make the
# CA-7 grep meaningless.
ALMOHADILLA: Final[str] = "#"

RAIZ: Final[Path] = Path(__file__).resolve().parents[2]
RUTA_FUENTE: Final[Path] = RAIZ / "docs" / "entregables" / "estilo" / "uxdoc.sty"
RUTA_TEX: Final[Path] = RAIZ / "docs" / "entregables" / "estilo" / "a4_tokens.tex"
RUTA_JSON: Final[Path] = RAIZ / "docs" / "entregables" / "datos" / "a4_tokens.json"

PATRON_DEFINECOLOR: Final[re.Pattern[str]] = re.compile(
    r"\\definecolor\{(\w+)\}\{HTML\}\{([0-9A-Fa-f]{6})\}"
)
PATRON_COLORLET: Final[re.Pattern[str]] = re.compile(r"\\colorlet\{(\w+)\}\{(\w+)\}")
PATRON_COMENTARIO: Final[re.Pattern[str]] = re.compile(r"(?<!\\)%.*$")

#: The eleven colours already versioned when A1, A2 and A3 were delivered.
#: Their value cannot change: three PDFs compile against them.
ANCLAS: Final[tuple[str, ...]] = (
    "uxnavy",
    "uxblue",
    "uxsky",
    "uxpale",
    "uxamber",
    "uxsurface",
    "uxink",
    "uxmuted",
    "uxline",
    "uxrow",
    "uxgreen",
)

TONOS_VALIDOS: Final[tuple[int, ...]] = (100, 300, 500, 700, 900)

Veredicto = Literal["AAA", "AA", "AA-grande", "falla"]

# (tono, nombre en uxdoc.sty, uso en prosa)
EspecTono = tuple[int, str, str]
# (clave, etiqueta, tonos)
EspecFamilia = tuple[str, str, tuple[EspecTono, ...]]
# (token css, tono nominal, nombre en uxdoc.sty, uso en prosa)
EspecToken = tuple[str, int, str, str]
# (frente, fondo, regla)
EspecPar = tuple[str, str, str]


@dataclass(frozen=True)
class Color:
    """A colour parsed from uxdoc.sty."""

    nombre_tex: str
    hex: str


@dataclass(frozen=True)
class Tono:
    """One step of a colour family, or one standalone token of the system."""

    nombre: str
    tono: int
    color: Color
    es_ancla: bool
    uso: str
    reusa: str | None = None

    @property
    def clase(self) -> str:
        """Tailwind utility that proves the token reaches the interface."""
        return f"bg-{self.nombre}"


@dataclass(frozen=True)
class Familia:
    """A five step colour family of the design system."""

    clave: str
    etiqueta: str
    tonos: tuple[Tono, ...]


@dataclass(frozen=True)
class Alias:
    """A US-001 token kept by name and derived from a step of the scale."""

    nombre: str
    origen: str
    tono: Tono


@dataclass(frozen=True)
class ParContraste:
    """A verified foreground/background pair."""

    frente: Tono
    fondo: Tono
    ratio: float
    veredicto: Veredicto
    regla: str


@dataclass(frozen=True)
class Hallazgo:
    """A contrast defect of the matrix together with the rule that replaces it."""

    numero: int
    par: ParContraste
    sustituto: ParContraste
    diagnostico: str


@dataclass(frozen=True)
class RolTipografico:
    """One of the nine roles of the type scale."""

    clave: str
    etiqueta: str
    tamano_px: int
    interlinea_px: int
    peso: int
    familia: str
    espaciado_em: float
    uso: str

    @property
    def clase(self) -> str:
        """Tailwind utility generated by the token."""
        return f"text-{self.clave}"


@dataclass(frozen=True)
class Sistema:
    """The whole design system, derived from a single stylesheet."""

    familias: tuple[Familia, ...]
    neutros: tuple[Tono, ...]
    semanticos: tuple[Tono, ...]
    series: tuple[Tono, ...]
    alias: tuple[Alias, ...]
    contrastes: tuple[ParContraste, ...]
    hallazgos: tuple[Hallazgo, ...]
    tipografia: tuple[RolTipografico, ...]

    @property
    def tokens(self) -> tuple[Tono, ...]:
        """Every colour token, in the order the guide prints them."""
        de_familias = tuple(tono for familia in self.familias for tono in familia.tonos)
        return de_familias + self.neutros + self.semanticos + self.series

    def tono(self, nombre: str) -> Tono:
        """Return the token named ``nombre``.

        Args:
            nombre: CSS token name without the ``--color-`` prefix.

        Returns:
            The matching token.

        Raises:
            KeyError: if no token carries that name.
        """
        for candidato in self.tokens:
            if candidato.nombre == nombre:
                return candidato
        raise KeyError(f"token de color desconocido: {nombre}")


ESPEC_FAMILIAS: Final[tuple[EspecFamilia, ...]] = (
    (
        "primary",
        "Primaria - azul institucional",
        (
            (100, "uxprimary100", "Relleno informativo y fondo de chip de estado."),
            (300, "uxprimary300", "Relleno de seleccion y de fila marcada."),
            (500, "uxblue", "Accion primaria, enlace y anillo de foco."),
            (700, "uxnavy", "Barra lateral, cabecera de tabla y titulares."),
            (900, "uxprimary900", "Fondo mas oscuro de la barra lateral colapsada."),
        ),
    ),
    (
        "secondary",
        "Secundaria - azul de grafica",
        (
            (100, "uxsecondary100", "Area bajo la curva de la serie secundaria."),
            (300, "uxpale", "Relleno suave, borde de tarjeta y area de banda."),
            (500, "uxsky", "Serie primaria de grafica y barra de progreso."),
            (700, "uxsecondary700", "Serie secundaria enfatizada y eje activo."),
            (900, "uxsecondary900", "Rejilla y eje sobre grafica de fondo oscuro."),
        ),
    ),
    (
        "accent",
        "Acento - ambar de uso escaso",
        (
            (100, "uxaccent100", "Fondo del aviso de alcance y del banner de demo."),
            (300, "uxaccent300", "Filete y relleno del aviso."),
            (500, "uxamber", "Solo decorativo: filete de marca. No informa."),
            (700, "uxaccent700", "Todo ambar que informa: icono, borde y marca."),
            (900, "uxaccent900", "Texto de aviso sobre el acento 100."),
        ),
    ),
    (
        "success",
        "Complemento - verde de confirmacion",
        (
            (100, "uxsuccess100", "Fondo de la insignia de confirmacion."),
            (300, "uxsuccess300", "Filete de la insignia de confirmacion."),
            (500, "uxsuccess500", "Marca grafica de confirmacion en tablero."),
            (700, "uxgreen", "Confirmacion en texto y estado correcto."),
            (900, "uxsuccess900", "Texto sobre el relleno de confirmacion."),
        ),
    ),
)

ESPEC_NEUTROS: Final[tuple[EspecToken, ...]] = (
    ("surface", 100, "uxsurface", "Superficie de pagina y de tarjeta."),
    ("surface-alt", 100, "uxrow", "Fila alterna de tabla y cabecera de panel."),
    ("line", 300, "uxline", "Filete decorativo y separador que no informa."),
    (
        "line-strong",
        500,
        "uxlinestrong",
        "Borde de campo de formulario y limite de componente que informa.",
    ),
    ("muted", 500, "uxmuted", "Texto secundario, solo a partir de 14 px."),
    ("ink", 700, "uxink", "Texto de cuerpo y cifra de tabla."),
    ("ink-strong", 900, "uxinkstrong", "Cifra de tarjeta KPI y titulo de dialogo."),
)

ESPEC_SEMANTICOS: Final[tuple[EspecToken, ...]] = (
    ("danger", 700, "uxdanger", "Error, campo invalido y accion destructiva."),
    ("danger-strong", 900, "uxdangerstrong", "Error enfatizado y titulo destructivo."),
    ("warning", 700, "uxwarning", "Aviso que informa; reusa el acento 700."),
    ("info", 500, "uxinfo", "Mensaje informativo; reusa la primaria 500."),
)

ESPEC_SERIES: Final[tuple[EspecToken, ...]] = (
    ("serie-1", 500, "uxserie1", "Serie 1 de grafica categorica."),
    ("serie-2", 700, "uxserie2", "Serie 2 de grafica categorica."),
    ("serie-3", 700, "uxserie3", "Serie 3 de grafica categorica."),
    ("serie-4", 500, "uxserie4", "Serie 4 de grafica categorica."),
    ("serie-5", 500, "uxserie5", "Serie 5 de grafica categorica."),
    ("serie-6", 700, "uxserie6", "Serie 6 de grafica categorica."),
)

#: US-001 wrote these names by hand and the prototype consumes them today.
#: They are kept as names and derived from the scale, never written apart.
ESPEC_ALIAS: Final[tuple[tuple[str, str], ...]] = (
    ("primary", "primary-500"),
    ("primary-dark", "primary-700"),
    ("secondary", "secondary-500"),
    ("secondary-soft", "secondary-300"),
    ("accent", "accent-500"),
    ("accent-text", "accent-900"),
    ("success", "success-700"),
)

ESPEC_PARES: Final[tuple[EspecPar, ...]] = (
    ("ink", "surface", "Texto de cuerpo sobre superficie: el par por omision."),
    ("ink", "surface-alt", "Texto de cuerpo sobre la fila alterna de la tabla."),
    ("ink-strong", "surface", "Cifra de tarjeta KPI, el neutro mas oscuro."),
    ("muted", "surface", "Texto secundario: solo a partir de 14 px, nunca una cifra."),
    ("muted", "surface-alt", "Texto secundario dentro de la tabla, mismo limite."),
    ("line", "surface", "Filete decorativo. No sirve de borde de campo."),
    ("line-strong", "surface", "Borde de campo de formulario y limite que informa."),
    ("line-strong", "surface-alt", "Borde de campo dentro de una fila alterna."),
    ("primary-700", "surface", "Titular de seccion y encabezado de tabla."),
    ("primary-500", "surface", "Enlace y texto de accion primaria."),
    ("primary-500", "surface-alt", "Enlace dentro de la tabla."),
    ("surface", "primary-500", "Texto del boton primario en reposo."),
    ("surface", "primary-700", "Texto de la barra lateral y de la cabecera."),
    ("surface", "primary-900", "Texto sobre el fondo mas oscuro de la barra."),
    ("ink", "primary-100", "Texto sobre el relleno informativo."),
    ("ink", "primary-300", "Texto sobre el relleno de seleccion."),
    ("secondary-500", "surface", "Serie de grafica: cumple el 3:1, no el de texto."),
    ("surface", "secondary-700", "Texto sobre la serie secundaria enfatizada."),
    ("surface", "secondary-900", "Texto sobre la grafica de fondo oscuro."),
    ("ink", "secondary-300", "Texto sobre el relleno suave del area bajo la curva."),
    ("ink", "secondary-100", "Texto sobre el area bajo la curva mas clara."),
    ("accent-500", "surface", "Hallazgo 3: el ambar 500 no informa, solo decora."),
    ("surface", "accent-500", "Hallazgo 1: el ambar 500 no lleva texto claro."),
    ("ink", "accent-500", "Regla sustituta de 1: sobre ambar 500, texto de tinta."),
    ("accent-700", "surface", "Regla sustituta de 3: el ambar que informa es el 700."),
    ("accent-700", "accent-100", "Hallazgo 2: el texto de aviso no puede ser el 700."),
    ("accent-900", "accent-100", "Regla sustituta de 2: el texto de aviso es el 900."),
    ("surface", "accent-700", "Texto claro sobre relleno de aviso solido."),
    ("ink", "accent-300", "Texto sobre el filete de aviso."),
    ("success-700", "surface", "Confirmacion en texto."),
    ("surface", "success-700", "Texto de la insignia de confirmacion."),
    ("success-500", "surface", "Marca grafica de confirmacion: 3:1 si, texto no."),
    ("ink", "success-100", "Texto sobre el relleno de confirmacion."),
    ("danger", "surface", "Error en texto y borde de campo invalido."),
    ("surface", "danger", "Texto del boton destructivo."),
    ("danger-strong", "surface", "Error enfatizado y titulo del dialogo destructivo."),
    ("warning", "surface", "Aviso como elemento grafico sobre superficie."),
    ("info", "surface", "Mensaje informativo en texto sobre superficie."),
    ("serie-1", "surface", "Serie 1 sobre superficie de grafica."),
    ("serie-2", "surface", "Serie 2 sobre superficie de grafica."),
    ("serie-3", "surface", "Serie 3 sobre superficie de grafica."),
    ("serie-4", "surface", "Serie 4 sobre superficie de grafica."),
    ("serie-5", "surface", "Serie 5 sobre superficie de grafica."),
    ("serie-6", "surface", "Serie 6 sobre superficie de grafica."),
)

# (numero, par medido, par sustituto, diagnostico)
ESPEC_HALLAZGOS: Final[tuple[tuple[int, str, str, str, str, str], ...]] = (
    (
        1,
        "surface",
        "accent-500",
        "ink",
        "accent-500",
        "La prosa del plan citaba 2.6:1 para el blanco sobre el ambar 500. El "
        "calculo WCAG 2.x da 2.80:1 con blanco puro y 2.68:1 con la superficie "
        "del producto, que es el claro que la interfaz usa de verdad. Los dos "
        "fallan: el veredicto no cambia, el numero si.",
    ),
    (
        2,
        "accent-700",
        "accent-100",
        "accent-900",
        "accent-100",
        "El texto de aviso en acento 700 sobre acento 100 se daba por bueno y "
        "queda por debajo del 4.5:1 de texto normal. El aviso pasa al acento "
        "900, que sube a AAA sin cambiar el fondo ni el tamano de letra.",
    ),
    (
        3,
        "accent-500",
        "surface",
        "accent-700",
        "surface",
        "El ambar 500 como elemento grafico informativo no llega al 3:1 que "
        "exige un limite de componente. Queda solo decorativo: todo ambar que "
        "informa usa el acento 700.",
    ),
    (
        4,
        "line",
        "surface",
        "line-strong",
        "surface",
        "El filete claro como borde de campo de formulario da 1.42:1, muy por "
        "debajo del 3:1 de limite de componente: el campo se veia como un "
        "rectangulo sin borde. El borde de campo usa el neutro fuerte y el "
        "filete claro queda para separadores decorativos.",
    ),
)

ESPEC_TIPOGRAFIA: Final[tuple[RolTipografico, ...]] = (
    RolTipografico(
        clave="display",
        etiqueta="Display",
        tamano_px=32,
        interlinea_px=40,
        peso=400,
        familia="display",
        espaciado_em=-0.01,
        uso="Cifra unica de portada de tablero y titulo de pantalla vacia.",
    ),
    RolTipografico(
        clave="titulo-1",
        etiqueta="Titulo 1",
        tamano_px=24,
        interlinea_px=32,
        peso=400,
        familia="display",
        espaciado_em=-0.01,
        uso="Titulo de pantalla, uno solo por vista.",
    ),
    RolTipografico(
        clave="titulo-2",
        etiqueta="Titulo 2",
        tamano_px=20,
        interlinea_px=28,
        peso=400,
        familia="display",
        espaciado_em=0.0,
        uso="Titulo de tarjeta, de panel y de lamina.",
    ),
    RolTipografico(
        clave="titulo-3",
        etiqueta="Titulo 3",
        tamano_px=16,
        interlinea_px=22,
        peso=400,
        familia="display",
        espaciado_em=0.0,
        uso="Subtitulo y encabezado de grupo de campos.",
    ),
    RolTipografico(
        clave="cuerpo",
        etiqueta="Cuerpo",
        tamano_px=14,
        interlinea_px=20,
        peso=400,
        familia="sans",
        espaciado_em=0.0,
        uso="Texto por omision de la interfaz densa.",
    ),
    RolTipografico(
        clave="cuerpo-amplio",
        etiqueta="Cuerpo amplio",
        tamano_px=16,
        interlinea_px=26,
        peso=400,
        familia="sans",
        espaciado_em=0.0,
        uso="Parrafo largo: ayuda, respuesta del asistente y aviso de alcance.",
    ),
    RolTipografico(
        clave="etiqueta",
        etiqueta="Etiqueta",
        tamano_px=12,
        interlinea_px=16,
        peso=400,
        familia="sans",
        espaciado_em=0.04,
        uso="Etiqueta de campo, encabezado de columna y texto de chip.",
    ),
    RolTipografico(
        clave="dato",
        etiqueta="Dato",
        tamano_px=18,
        interlinea_px=24,
        peso=400,
        familia="sans",
        espaciado_em=0.0,
        uso="Cifra de tarjeta KPI y celda numerica, con cifras tabulares.",
    ),
    RolTipografico(
        clave="micro",
        etiqueta="Micro",
        tamano_px=11,
        interlinea_px=16,
        peso=400,
        familia="sans",
        espaciado_em=0.0,
        uso="Nota al pie, marca de tiempo y leyenda de grafica.",
    ),
)

ESCALA_ESPACIADO: Final[tuple[int, ...]] = (4, 8, 12, 16, 24, 32, 48, 64)

ESPEC_RADIOS: Final[tuple[tuple[str, int, str], ...]] = (
    ("sm", 4, "Chip, insignia y campo de una linea."),
    ("md", 6, "Boton, campo de formulario y celda de tabla activa."),
    ("lg", 10, "Tarjeta, panel y dialogo."),
    ("full", 999, "Avatar, punto de estado y boton circular de icono."),
)

ESPEC_SOMBRAS: Final[tuple[tuple[str, str, str], ...]] = (
    ("reposo", "0 1px 2px 0", "Tarjeta y tabla en reposo."),
    ("elevado", "0 2px 6px -1px", "Tarjeta al pasar el puntero y menu abierto."),
    ("flotante", "0 8px 24px -6px", "Dialogo, panel lateral y sugerencia flotante."),
)

ESPEC_OPACIDAD_SOMBRA: Final[tuple[float, ...]] = (0.06, 0.10, 0.18)

ESPEC_QUIEBRES: Final[tuple[tuple[str, int, str], ...]] = (
    ("sm", 768, "Tableta vertical: la barra lateral se colapsa a iconos."),
    ("md", 1024, "Tableta horizontal: vuelve la barra lateral con etiqueta."),
    ("lg", 1280, "Escritorio: aparece la segunda columna del tablero."),
    ("xl", 1440, "Escritorio ancho: ancho de captura de las figuras de A4."),
)

ESPEC_DENSIDAD: Final[tuple[tuple[str, int, str], ...]] = (
    ("sidebar-width", 240, "Ancho de la barra lateral desplegada."),
    ("header-height", 56, "Alto de la cabecera fija."),
    ("grid-gap", 8, "Canal entre columnas de la reticula de 12."),
    ("card-padding", 12, "Relleno interno de tarjeta y de panel."),
    ("table-row-height", 36, "Alto de fila de tabla densa."),
)

REGLAS_DERIVADAS: Final[tuple[str, ...]] = (
    "El acento 500 no lleva texto claro encima: con la superficie del producto "
    "da 2.68:1 y con blanco puro 2.80:1. Si el ambar 500 lleva texto, el texto "
    "es tinta (5.22:1).",
    "Todo ambar que informa usa el acento 700 (4.40:1 sobre superficie, por "
    "encima del 3:1 de elemento grafico). El acento 500 queda decorativo.",
    "El texto de aviso es el acento 900 sobre el acento 100 (7.58:1, AAA). El "
    "acento 700 sobre el mismo fondo se queda en 3.96:1 y falla AA.",
    "El borde de campo de formulario usa el neutro line-strong (4.55:1). El "
    "filete claro line (1.42:1) queda para separadores decorativos.",
    "El neutro muted solo rotula texto de 14 px o mas (4.55:1, AA justo): "
    "ninguna cifra ni etiqueta menor va en muted.",
)


def leer_definecolor(ruta: Path) -> dict[str, Color]:
    r"""Read every colour declaration of the stylesheet, in file order.

    Both forms are read. ``\\definecolor`` declares a value; ``\\colorlet``
    declares an alias and resolves to the very same object, so a reused colour
    cannot drift from the anchor it reuses.

    Args:
        ruta: Path of uxdoc.sty, the single source of colour.

    Returns:
        Mapping from TeX colour name to the parsed colour.

    Raises:
        ValueError: if an alias points at a name that was not declared before.
    """
    colores: dict[str, Color] = {}
    for linea in ruta.read_text(encoding="utf-8").splitlines():
        limpia = PATRON_COMENTARIO.sub("", linea)
        declaracion = PATRON_DEFINECOLOR.search(limpia)
        if declaracion is not None:
            nombre, valor = declaracion.groups()
            colores[nombre] = Color(nombre_tex=nombre, hex=ALMOHADILLA + valor.upper())
            continue
        alias = PATRON_COLORLET.search(limpia)
        if alias is not None:
            nombre, origen = alias.groups()
            if origen not in colores:
                raise ValueError(
                    f"el alias {nombre} apunta a {origen}, que no esta declarado"
                )
            colores[nombre] = colores[origen]
    return colores


def luminancia_relativa(hex_color: str) -> float:
    """Relative luminance of a colour, as defined by WCAG 2.x.

    Args:
        hex_color: Colour in six digit hexadecimal notation with a leading hash.

    Returns:
        Relative luminance between 0 and 1.
    """
    crudo = hex_color.lstrip(ALMOHADILLA)
    canales = [int(crudo[posicion : posicion + 2], 16) / 255 for posicion in (0, 2, 4)]
    lineales = [
        canal / 12.92 if canal <= 0.03928 else ((canal + 0.055) / 1.055) ** 2.4
        for canal in canales
    ]
    return 0.2126 * lineales[0] + 0.7152 * lineales[1] + 0.0722 * lineales[2]


def razon_de_contraste(frente: str, fondo: str) -> float:
    """Contrast ratio of two colours, as defined by WCAG 2.x.

    Args:
        frente: Foreground colour in hexadecimal notation.
        fondo: Background colour in hexadecimal notation.

    Returns:
        Ratio between 1 and 21. The order of the arguments does not matter.
    """
    luminancias = (luminancia_relativa(frente), luminancia_relativa(fondo))
    return (max(luminancias) + 0.05) / (min(luminancias) + 0.05)


def _veredicto(ratio: float) -> Veredicto:
    """Classify a rounded ratio against the WCAG 2.x thresholds."""
    if ratio >= 7.0:
        return "AAA"
    if ratio >= 4.5:
        return "AA"
    if ratio >= 3.0:
        return "AA-grande"
    return "falla"


def _rgb(color: Color) -> str:
    """Space separated RGB channels of a colour, for the CSS shadow syntax."""
    crudo = color.hex.lstrip(ALMOHADILLA)
    canales = (int(crudo[posicion : posicion + 2], 16) for posicion in (0, 2, 4))
    return " ".join(str(canal) for canal in canales)


def _tomar(colores: dict[str, Color], nombre_tex: str) -> Color:
    """Return a declared colour or fail loudly.

    Args:
        colores: Colours parsed from the stylesheet.
        nombre_tex: Name the specification expects to find.

    Returns:
        The declared colour.

    Raises:
        ValueError: if the stylesheet does not declare that name.
    """
    if nombre_tex not in colores:
        raise ValueError(
            f"uxdoc.sty no declara {nombre_tex}: la escala y la fuente divergieron"
        )
    return colores[nombre_tex]


def _duenos() -> dict[str, str]:
    r"""Map every TeX colour name to the token that declares it as its own.

    An alias declared with ``\\colorlet`` resolves to the anchor object, so a
    token whose parsed name differs from the one its specification declares is
    reusing the token that owns that name. The map makes the reuse explicit in
    the guide instead of leaving it as a coincidence of equal values.

    Returns:
        Mapping from TeX colour name to CSS token name.
    """
    mapa: dict[str, str] = {}
    for clave, _, espec_tonos in ESPEC_FAMILIAS:
        for tono, nombre_tex, _uso in espec_tonos:
            mapa[nombre_tex] = f"{clave}-{tono}"
    for espec in (*ESPEC_NEUTROS, *ESPEC_SEMANTICOS, *ESPEC_SERIES):
        nombre, _tono, nombre_tex, _uso = espec
        mapa[nombre_tex] = nombre
    return mapa


def _construir_token(colores: dict[str, Color], espec: EspecToken) -> Tono:
    """Build one standalone token of the system from its specification."""
    nombre, tono, nombre_tex, uso = espec
    color = _tomar(colores, nombre_tex)
    reusa = _duenos().get(color.nombre_tex) if color.nombre_tex != nombre_tex else None
    return Tono(
        nombre=nombre,
        tono=tono,
        color=color,
        es_ancla=color.nombre_tex in ANCLAS,
        uso=uso,
        reusa=reusa,
    )


def construir_sistema(colores: dict[str, Color]) -> Sistema:
    """Assemble the design system from the parsed colours.

    Args:
        colores: Colours parsed from uxdoc.sty.

    Returns:
        The whole system: families, neutrals, semantics, series, aliases,
        contrast matrix, findings and type scale.

    Raises:
        ValueError: if the stylesheet lost an anchor, if a family stops being
            monotonic or if the token count leaves the 37 of the guide.
    """
    faltantes = [ancla for ancla in ANCLAS if ancla not in colores]
    if faltantes:
        raise ValueError(f"uxdoc.sty perdio anclas versionadas: {faltantes}")

    familias: list[Familia] = []
    for clave, etiqueta, espec_tonos in ESPEC_FAMILIAS:
        tonos = [
            _construir_token(colores, (f"{clave}-{tono}", tono, nombre_tex, uso))
            for tono, nombre_tex, uso in espec_tonos
        ]
        luminancias = [luminancia_relativa(paso.color.hex) for paso in tonos]
        if any(anterior <= siguiente for anterior, siguiente in pairwise(luminancias)):
            raise ValueError(
                f"la familia {clave} no oscurece de forma monotona del 100 al 900"
            )
        familias.append(Familia(clave=clave, etiqueta=etiqueta, tonos=tuple(tonos)))

    neutros = tuple(_construir_token(colores, espec) for espec in ESPEC_NEUTROS)
    semanticos = tuple(_construir_token(colores, espec) for espec in ESPEC_SEMANTICOS)
    series = tuple(_construir_token(colores, espec) for espec in ESPEC_SERIES)

    parcial = Sistema(
        familias=tuple(familias),
        neutros=neutros,
        semanticos=semanticos,
        series=series,
        alias=(),
        contrastes=(),
        hallazgos=(),
        tipografia=ESPEC_TIPOGRAFIA,
    )

    esperados = 5 * len(ESPEC_FAMILIAS) + len(neutros) + len(semanticos) + len(series)
    if len(parcial.tokens) != esperados:
        raise ValueError(f"el sistema declara {len(parcial.tokens)} tokens de color")

    anclas_vivas = {
        token.color.nombre_tex for token in parcial.tokens if token.es_ancla
    }
    if anclas_vivas != set(ANCLAS):
        raise ValueError(
            "la escala dejo de usar alguna de las once anclas versionadas: "
            f"{sorted(set(ANCLAS) - anclas_vivas)}"
        )

    alias = tuple(
        Alias(nombre=nombre, origen=origen, tono=parcial.tono(origen))
        for nombre, origen in ESPEC_ALIAS
    )
    contrastes = tuple(
        _par(parcial, frente, fondo, regla) for frente, fondo, regla in ESPEC_PARES
    )
    hallazgos = tuple(
        Hallazgo(
            numero=numero,
            par=_buscar_par(contrastes, frente, fondo),
            sustituto=_buscar_par(contrastes, frente_ok, fondo_ok),
            diagnostico=diagnostico,
        )
        for numero, frente, fondo, frente_ok, fondo_ok, diagnostico in ESPEC_HALLAZGOS
    )

    return Sistema(
        familias=parcial.familias,
        neutros=neutros,
        semanticos=semanticos,
        series=series,
        alias=alias,
        contrastes=contrastes,
        hallazgos=hallazgos,
        tipografia=ESPEC_TIPOGRAFIA,
    )


def _par(sistema: Sistema, frente: str, fondo: str, regla: str) -> ParContraste:
    """Measure one foreground/background pair of the matrix."""
    tono_frente = sistema.tono(frente)
    tono_fondo = sistema.tono(fondo)
    ratio = round(razon_de_contraste(tono_frente.color.hex, tono_fondo.color.hex), 2)
    return ParContraste(
        frente=tono_frente,
        fondo=tono_fondo,
        ratio=ratio,
        veredicto=_veredicto(ratio),
        regla=regla,
    )


def _buscar_par(
    contrastes: tuple[ParContraste, ...], frente: str, fondo: str
) -> ParContraste:
    """Return the measured pair with those two tokens.

    Args:
        contrastes: Matrix already measured.
        frente: Foreground token name.
        fondo: Background token name.

    Returns:
        The matching pair.

    Raises:
        ValueError: if the matrix does not cover the pair a finding cites.
    """
    for par in contrastes:
        if par.frente.nombre == frente and par.fondo.nombre == fondo:
            return par
    raise ValueError(f"la matriz no mide el par {frente} sobre {fondo}")


def _cabecera(marca: str) -> list[str]:
    """Build the "generated, do not edit" banner shared by the four outputs.

    Args:
        marca: Comment prefix of the target language.

    Returns:
        The banner lines, already prefixed and without trailing spaces.
    """
    cuerpo = (
        f"Guia de estilos de Karisma Data {VERSION_GUIA} - {FECHA_GUIA}",
        "",
        "GENERADO. No editar a mano: cualquier cambio se pierde en la siguiente",
        "corrida y hace divergir la aplicacion del PDF del curso.",
        "",
        "Fuente unica: docs/entregables/estilo/uxdoc.sty",
        "Generador:    docs/entregables/generar_tokens_a4.py",
        "Regenerar:    make tokens",
        "Verificar:    python docs/entregables/generar_tokens_a4.py --verificar",
    )
    return [f"{marca} {texto}".rstrip() for texto in cuerpo]


def emitir_theme_css(sistema: Sistema) -> str:
    """Render the palette of the report as a Tailwind v4 ``@theme`` block.

    Nothing writes this anywhere. ``frontend/app/assets/css/main.css`` belongs
    to ``design/emitir.py``, and pointing this text back at it is the defect
    that ``docs/us-backlog/11-make-tokens-destruye-los-tokens-del-portal.md``
    describes. It stays because the contract tests read it to check that every
    alias of US-001 takes its value from its step of the scale.

    Args:
        sistema: The design system.

    Returns:
        The palette of the report written as a ``@theme`` block.
    """
    lineas: list[str] = [
        "/* Paleta del informe en forma de @theme - generado, no editar a mano */",
        "/*",
        *_cabecera(" *"),
        " *",
        " * Esta hoja NO es la del portal: main.css sale de design/sistema.py y",
        " * lo publica design/emitir.py. Aqui la derivacion va en un solo",
        " * sentido, uxdoc.sty -> laminas -> PDF, y nada fluye hacia atras.",
        " */",
        '@import "tailwindcss";',
        "",
        "@theme {",
    ]

    def bloque(titulo: str) -> None:
        lineas.append(f"  /* {titulo} */")

    def token(nombre: str, valor: str, nota: str) -> None:
        declaracion = f"  --{nombre}: {valor};"
        lineas.append(f"{declaracion:<40} /* {nota} */")

    def color(tono: Tono) -> None:
        marca = " (ancla)" if tono.es_ancla else ""
        reuso = f" (= {tono.reusa})" if tono.reusa else ""
        token(
            f"color-{tono.nombre}",
            tono.color.hex,
            f"{tono.color.nombre_tex}{marca}{reuso} - {tono.uso}",
        )

    for familia in sistema.familias:
        bloque(familia.etiqueta)
        for paso in familia.tonos:
            color(paso)
        lineas.append("")

    for titulo, grupo in (
        ("Neutros - sin negro ni blanco puros", sistema.neutros),
        ("Semanticos - el aviso y el informativo reusan la escala", sistema.semanticos),
        (
            "Serie categorica de grafica - todas con 3:1 o mas sobre la superficie",
            sistema.series,
        ),
    ):
        bloque(titulo)
        for tono in grupo:
            color(tono)
        lineas.append("")

    bloque("Alias de US-001 - derivados de la escala, nunca escritos aparte")
    for alias in sistema.alias:
        token(f"color-{alias.nombre}", alias.tono.color.hex, f"= {alias.origen}")
    lineas.append("")

    bloque("Tipografia - dos familias servidas desde el propio origen")
    token("font-display", '"Lexend Deca", sans-serif', "Titulares")
    token("font-sans", '"Fira Sans", sans-serif', "Cuerpo")
    lineas.append("")

    bloque("Escala tipografica - 9 roles. El peso no construye jerarquia")
    for rol in sistema.tipografia:
        token(f"text-{rol.clave}", f"{rol.tamano_px}px", rol.uso)
        lineas.append(f"  --text-{rol.clave}--line-height: {rol.interlinea_px}px;")
        lineas.append(f"  --text-{rol.clave}--font-weight: {rol.peso};")
        if rol.espaciado_em:
            lineas.append(
                f"  --text-{rol.clave}--letter-spacing: {rol.espaciado_em}em;"
            )
    lineas.append("")

    bloque(
        "Ritmo de espaciado en base 4: Tailwind deriva "
        + "/".join(str(paso) for paso in ESCALA_ESPACIADO)
    )
    token("spacing", f"{ESCALA_ESPACIADO[0]}px", "unidad del ritmo")
    lineas.append("")

    bloque("Radios")
    for nombre, valor, uso in ESPEC_RADIOS:
        token(f"radius-{nombre}", f"{valor}px", uso)
    lineas.append("")

    tinta = sistema.tono("ink-strong").color
    bloque("Sombras - un solo color de sombra, la tinta mas oscura del sistema")
    for (nombre, desplazamiento, uso), opacidad in zip(
        ESPEC_SOMBRAS, ESPEC_OPACIDAD_SOMBRA, strict=True
    ):
        token(
            f"shadow-{nombre}",
            f"{desplazamiento} rgb({_rgb(tinta)} / {opacidad})",
            uso,
        )
    lineas.append("")

    bloque("Puntos de quiebre")
    for nombre, valor, uso in ESPEC_QUIEBRES:
        token(f"breakpoint-{nombre}", f"{valor}px", uso)
    lineas.append("")

    bloque("Densidad - ficha Data-Dense Dashboard de ui-ux-pro-max")
    for nombre, valor, uso in ESPEC_DENSIDAD:
        token(nombre, f"{valor}px", uso)

    lineas.append("}")
    return "\n".join(lineas) + "\n"


def _cadena_ts(texto: str) -> str:
    """Quote a Spanish string for TypeScript, escaping what the linter forbids."""
    escapado = texto.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escapado}'"


def _tono_ts(tono: Tono, sangria: str) -> list[str]:
    """Serialise one token as a TypeScript object literal."""
    lineas = [
        f"{sangria}{{",
        f"{sangria}  nombre: {_cadena_ts(tono.nombre)},",
        f"{sangria}  tono: {tono.tono},",
        f"{sangria}  hex: {_cadena_ts(tono.color.hex)},",
        f"{sangria}  clase: {_cadena_ts(tono.clase)},",
        f"{sangria}  nombreTex: {_cadena_ts(tono.color.nombre_tex)},",
        f"{sangria}  esAncla: {'true' if tono.es_ancla else 'false'},",
        f"{sangria}  reusa: {_cadena_ts(tono.reusa) if tono.reusa else 'null'},",
        f"{sangria}  uso: {_cadena_ts(tono.uso)},",
        f"{sangria}}},",
    ]
    return lineas


def _par_ts(par: ParContraste, sangria: str) -> list[str]:
    """Serialise one contrast pair as a TypeScript object literal."""
    return [
        f"{sangria}{{",
        f"{sangria}  frente: {_cadena_ts(par.frente.nombre)},",
        f"{sangria}  frenteHex: {_cadena_ts(par.frente.color.hex)},",
        f"{sangria}  fondo: {_cadena_ts(par.fondo.nombre)},",
        f"{sangria}  fondoHex: {_cadena_ts(par.fondo.color.hex)},",
        f"{sangria}  ratio: {par.ratio},",
        f"{sangria}  veredicto: {_cadena_ts(par.veredicto)},",
        f"{sangria}  regla: {_cadena_ts(par.regla)},",
        f"{sangria}}},",
    ]


def emitir_tokens_ts(sistema: Sistema) -> str:
    """Render the palette of the report as a typed TypeScript module.

    Nothing writes this anywhere either: ``frontend/app/utils/tokens.generated.ts``
    belongs to ``design/emitir.py``. It stays because the contract tests read it
    to check that the version is the same in every rendering of the guide.

    Args:
        sistema: The design system.

    Returns:
        The palette of the report written as a typed module.
    """
    lineas: list[str] = [
        "/**",
        *_cabecera(" *"),
        " *",
        " * The guide prints these values, so no hex is typed inside a Vue file.",
        " */",
        "",
        "/** One step of a colour family, or one standalone token of the system. */",
        "export interface TonoToken {",
        "  readonly nombre: string",
        "  readonly tono: 100 | 300 | 500 | 700 | 900",
        "  readonly hex: string",
        "  readonly clase: string",
        "  readonly nombreTex: string",
        "  readonly esAncla: boolean",
        "  readonly reusa: string | null",
        "  readonly uso: string",
        "}",
        "",
        "/** A five step colour family of the design system. */",
        "export interface FamiliaToken {",
        "  readonly clave: 'primary' | 'secondary' | 'accent' | 'success'",
        "  readonly etiqueta: string",
        "  readonly tonos: readonly TonoToken[]",
        "}",
        "",
        "/** A foreground/background pair verified with the WCAG 2.x formula. */",
        "export interface ParContrasteToken {",
        "  readonly frente: string",
        "  readonly frenteHex: string",
        "  readonly fondo: string",
        "  readonly fondoHex: string",
        "  readonly ratio: number",
        "  readonly veredicto: 'AAA' | 'AA' | 'AA-grande' | 'falla'",
        "  readonly regla: string",
        "}",
        "",
        "/** A contrast defect and the rule that replaces it. */",
        "export interface HallazgoToken {",
        "  readonly numero: number",
        "  readonly par: ParContrasteToken",
        "  readonly sustituto: ParContrasteToken",
        "  readonly diagnostico: string",
        "}",
        "",
        "/** One of the nine roles of the type scale. */",
        "export interface RolTipografico {",
        "  readonly clave: string",
        "  readonly etiqueta: string",
        "  readonly clase: string",
        "  readonly tamanoPx: number",
        "  readonly interlineaPx: number",
        "  readonly peso: number",
        "  readonly familia: 'display' | 'sans'",
        "  readonly uso: string",
        "}",
        "",
        f"export const VERSION_GUIA = {_cadena_ts(VERSION_GUIA)}",
        "",
        f"export const FECHA_GUIA = {_cadena_ts(FECHA_GUIA)}",
        "",
        "/** The four families of the brand, five steps each. */",
        "export const FAMILIAS: readonly FamiliaToken[] = Object.freeze([",
    ]
    for familia in sistema.familias:
        lineas += [
            "  {",
            f"    clave: {_cadena_ts(familia.clave)},",
            f"    etiqueta: {_cadena_ts(familia.etiqueta)},",
            "    tonos: [",
        ]
        for paso in familia.tonos:
            lineas += _tono_ts(paso, "      ")
        lineas += ["    ],", "  },"]
    lineas.append("])")
    lineas.append("")

    for constante, comentario, tokens in (
        (
            "NEUTROS",
            "The seven neutrals. No pure black and no pure white.",
            sistema.neutros,
        ),
        ("SEMANTICOS", "The four semantic tokens.", sistema.semanticos),
        ("SERIES", "The six categorical chart colours.", sistema.series),
    ):
        lineas.append(f"/** {comentario} */")
        lineas.append(
            f"export const {constante}: readonly TonoToken[] = Object.freeze(["
        )
        for tono in tokens:
            lineas += _tono_ts(tono, "  ")
        lineas += ["])", ""]

    lineas.append("/** Every pair measured with the WCAG 2.x formula. */")
    lineas.append(
        "export const CONTRASTES: readonly ParContrasteToken[] = Object.freeze(["
    )
    for par in sistema.contrastes:
        lineas += _par_ts(par, "  ")
    lineas += ["])", ""]

    lineas.append(
        "/** The four defects the matrix found, with their substitute rule. */"
    )
    lineas.append("export const HALLAZGOS: readonly HallazgoToken[] = Object.freeze([")
    for hallazgo in sistema.hallazgos:
        lineas += [
            "  {",
            f"    numero: {hallazgo.numero},",
            "    par: {",
        ]
        lineas += _par_ts(hallazgo.par, "    ")[1:-1]
        lineas += ["    },", "    sustituto: {"]
        lineas += _par_ts(hallazgo.sustituto, "    ")[1:-1]
        lineas += [
            "    },",
            f"    diagnostico: {_cadena_ts(hallazgo.diagnostico)},",
            "  },",
        ]
    lineas += ["])", ""]

    lineas.append("/** The five rules the contrast matrix produced. */")
    lineas.append("export const REGLAS_DERIVADAS: readonly string[] = Object.freeze([")
    for regla in REGLAS_DERIVADAS:
        lineas.append(f"  {_cadena_ts(regla)},")
    lineas += ["])", ""]

    lineas.append("/** The nine roles of the type scale. */")
    lineas.append(
        "export const ESCALA_TIPOGRAFICA: readonly RolTipografico[] = Object.freeze(["
    )
    for rol in sistema.tipografia:
        lineas += [
            "  {",
            f"    clave: {_cadena_ts(rol.clave)},",
            f"    etiqueta: {_cadena_ts(rol.etiqueta)},",
            f"    clase: {_cadena_ts(rol.clase)},",
            f"    tamanoPx: {rol.tamano_px},",
            f"    interlineaPx: {rol.interlinea_px},",
            f"    peso: {rol.peso},",
            f"    familia: {_cadena_ts(rol.familia)},",
            f"    uso: {_cadena_ts(rol.uso)},",
            "  },",
        ]
    lineas += ["])", ""]

    espaciado = ", ".join(str(paso) for paso in ESCALA_ESPACIADO)
    lineas += [
        "/** The 4 based spacing rhythm, in pixels. */",
        "export const ESCALA_ESPACIADO: readonly number[] = "
        f"Object.freeze([{espaciado}])",
        "",
    ]
    return "\n".join(lineas)


def _texto_tex(texto: str) -> str:
    """Escape the characters LaTeX would read as markup."""
    reemplazos = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        ALMOHADILLA: r"\#",
    }
    return "".join(reemplazos.get(caracter, caracter) for caracter in texto)


def _muestra_tex(tono: Tono) -> str:
    """Colour swatch of a token, drawn as a rule so it survives a photocopy."""
    return f"{{\\color{{{tono.color.nombre_tex}}}\\rule{{0.85cm}}{{0.30cm}}}}"


def emitir_laminas_tex(sistema: Sistema) -> str:
    """Emit the four LaTeX plates of the style guide.

    The plates are macros, not sections: the writer of the document places each
    one under its own subtitle. They are LaTeX and not PNG on purpose, so the
    type specimen uses the very families uxdoc.sty loads with fontspec.

    Args:
        sistema: The design system.

    Returns:
        Full content of ``docs/entregables/estilo/a4_tokens.tex``.
    """
    lineas: list[str] = [
        "%% " + "=" * 74,
        *_cabecera("%% "),
        "%%",
        "%%  Uso desde el documento:",
        "%%    \\input{estilo/a4_tokens}",
        "%%    \\laminaPaleta  \\laminaContraste  \\laminaTipografia  \\laminaReticula",
        "%% " + "=" * 74,
        "",
        f"\\newcommand{{\\versionguia}}{{{VERSION_GUIA}}}",
        f"\\newcommand{{\\fechaguia}}{{{FECHA_GUIA_LARGA}}}",
        "",
    ]

    # ---- Lamina 1: paleta -------------------------------------------------
    lineas += [
        "% Lamina 1. Paleta completa: 37 tokens derivados de uxdoc.sty.",
        "\\newcommand{\\laminaPaleta}{%",
        "\\begin{uxtablalarga}{@{}C{1.0cm} L{2.7cm} L{1.9cm} L{2.5cm} Y@{}}%",
        "{Paleta del sistema de dise\\~no: 37 tokens de color emitidos desde "
        "\\texttt{uxdoc.sty}}%",
        "{\\thd{Color} & \\thd{Token} & \\thd{Hexadecimal} & "
        "\\thd{Nombre en TeX} & \\thd{Uso}}",
    ]
    grupos: tuple[tuple[str, tuple[Tono, ...]], ...] = (
        *((familia.etiqueta, familia.tonos) for familia in sistema.familias),
        ("Neutros", sistema.neutros),
        ("Semanticos", sistema.semanticos),
        ("Serie categorica de grafica", sistema.series),
    )
    for etiqueta, tokens in grupos:
        lineas.append(
            f"\\multicolumn{{5}}{{@{{}}l@{{}}}}{{\\color{{uxnavy}}\\small "
            f"{_texto_tex(etiqueta)}}} \\\\"
        )
        for tono in tokens:
            marca = "*" if tono.es_ancla else ""
            reuso = f" Reusa {_texto_tex(tono.reusa)}." if tono.reusa else ""
            lineas.append(
                f"{_muestra_tex(tono)} & "
                f"\\texttt{{{_texto_tex(tono.nombre)}}}{marca} & "
                f"\\texttt{{{_texto_tex(tono.color.hex)}}} & "
                f"\\texttt{{{_texto_tex(tono.color.nombre_tex)}}} & "
                f"{_texto_tex(tono.uso)}{reuso} \\\\"
            )
    lineas += [
        "\\end{uxtablalarga}",
        "\\vspace{-6pt}{\\footnotesize\\color{uxmuted}Los tokens marcados con "
        "asterisco usan uno de los once colores anclados en la Actividad 1: su "
        "valor no cambia porque tres documentos entregados compilan contra "
        "ellos. Los tokens con la nota \\enquote{reusa} apuntan al color ancla "
        "con \\texttt{\\textbackslash{}colorlet}, de modo que no pueden "
        "divergir de el.\\par}%",
        "}",
        "",
    ]

    # ---- Lamina 2: matriz de contraste ------------------------------------
    conteo = len(sistema.contrastes)
    lineas += [
        "% Lamina 2. Matriz de contraste calculada con la formula WCAG 2.x.",
        "\\newcommand{\\laminaContraste}{%",
        "\\begin{uxtablalarga}{@{}L{2.5cm} L{2.5cm} C{1.4cm} C{1.7cm} Y@{}}%",
        f"{{Matriz de contraste: {conteo} pares calculados con la f\\'ormula "
        "WCAG 2.x (luminancia relativa y $(L_1+0{,}05)/(L_2+0{,}05)$)}%",
        "{\\thd{Frente} & \\thd{Fondo} & \\thd{Raz\\'on} & \\thd{Veredicto} & "
        "\\thd{Regla}}",
    ]
    for par in sistema.contrastes:
        color_veredicto = {
            "AAA": "uxgreen",
            "AA": "uxgreen",
            "AA-grande": "uxaccent700",
            "falla": "uxdanger",
        }[par.veredicto]
        lineas.append(
            f"\\texttt{{{_texto_tex(par.frente.nombre)}}} & "
            f"\\texttt{{{_texto_tex(par.fondo.nombre)}}} & "
            f"{par.ratio:.2f}:1 & "
            f"\\textcolor{{{color_veredicto}}}{{{_texto_tex(par.veredicto)}}} & "
            f"{_texto_tex(par.regla)} \\\\"
        )
    lineas += ["\\end{uxtablalarga}", ""]
    lineas += [
        "\\begin{uxtablalarga}{@{}C{0.9cm} L{4.2cm} C{1.4cm} Z{1.2} Z{0.8}@{}}%",
        "{Los cuatro defectos que la matriz encontr\\'o y la regla que los sustituye}%",
        "{\\thd{\\#} & \\thd{Par medido} & \\thd{Raz\\'on} & \\thd{Diagn\\'ostico} "
        "& \\thd{Regla sustituta}}",
    ]
    for hallazgo in sistema.hallazgos:
        sustituto = (
            f"\\texttt{{{_texto_tex(hallazgo.sustituto.frente.nombre)}}} sobre "
            f"\\texttt{{{_texto_tex(hallazgo.sustituto.fondo.nombre)}}}: "
            f"{hallazgo.sustituto.ratio:.2f}:1 "
            f"({_texto_tex(hallazgo.sustituto.veredicto)})"
        )
        lineas.append(
            f"{hallazgo.numero} & "
            f"\\texttt{{{_texto_tex(hallazgo.par.frente.nombre)}}} sobre "
            f"\\texttt{{{_texto_tex(hallazgo.par.fondo.nombre)}}} & "
            f"\\textcolor{{uxdanger}}{{{hallazgo.par.ratio:.2f}:1}} & "
            f"{_texto_tex(hallazgo.diagnostico)} & {sustituto} \\\\"
        )
    lineas += ["\\end{uxtablalarga}", ""]
    lineas += [
        "{\\color{uxnavy}\\small Reglas derivadas de la matriz\\par}",
        "\\begin{enumerate}[leftmargin=*,itemsep=2pt,topsep=4pt]",
    ]
    for regla in REGLAS_DERIVADAS:
        lineas.append(f"\\item {_texto_tex(regla)}")
    lineas += ["\\end{enumerate}", "}", ""]

    # ---- Lamina 3: escala tipografica -------------------------------------
    lineas += [
        "% Lamina 3. Especimen de los nueve roles, compuesto con las familias",
        "% reales del producto: fontspec ya las carga en uxdoc.sty.",
        "\\newcommand{\\laminaTipografia}{%",
        "\\begingroup\\setlength{\\parskip}{4pt}%",
    ]
    for rol in sistema.tipografia:
        familia_tex = "\\uxhead" if rol.familia == "display" else "\\sffamily"
        nombre_familia = "Lexend Deca" if rol.familia == "display" else "Fira Sans"
        lineas += [
            f"{{{familia_tex}\\fontsize{{{rol.tamano_px * 0.75:.2f}}}"
            f"{{{rol.interlinea_px * 0.75:.2f}}}\\selectfont "
            "Karisma Data Aa Bb 0123456789\\par}",
            f"{{\\footnotesize\\color{{uxmuted}}\\texttt{{{_texto_tex(rol.clase)}}} "
            f"- {rol.tamano_px} px / {rol.interlinea_px} px "
            f"({rol.tamano_px * 0.75:.2f} pt / {rol.interlinea_px * 0.75:.2f} pt) "
            f"- {nombre_familia} {rol.peso} - {_texto_tex(rol.uso)}\\par}}",
        ]
    lineas += [
        "\\endgroup",
        "\\vspace{2pt}{\\footnotesize\\color{uxmuted}Los nueve roles usan el peso "
        "400. La jerarqu\\'ia se construye con tama\\~no, color y espacio en "
        "blanco, no con peso: Lexend Deca se distribuye solo en Regular y el "
        "m\\'odulo de fuentes descarga esa \\'unica variante, as\\'i que un peso "
        "mayor producir\\'ia negrita simulada distinta en la pantalla y en el "
        "PDF.\\par}%",
        "}",
        "",
    ]

    # ---- Lamina 4: reticula y espaciado -----------------------------------
    lineas += [
        "% Lamina 4. Ritmo de 4 px, radios, sombras, quiebres y densidad.",
        "\\newcommand{\\laminaReticula}{%",
        "\\begin{uxtablalarga}{@{}C{1.5cm} C{1.8cm} Y@{}}%",
        "{Ritmo de espaciado en base 4 del que Tailwind deriva los ocho pasos}%",
        "{\\thd{Paso} & \\thd{Medida} & \\thd{Barra a escala}}",
    ]
    for paso in ESCALA_ESPACIADO:
        lineas.append(
            f"\\texttt{{{paso // ESCALA_ESPACIADO[0]}}} & {paso} px & "
            f"{{\\color{{uxsky}}\\rule{{{paso * 0.75:.2f}pt}}{{0.22cm}}}} \\\\"
        )
    lineas += ["\\end{uxtablalarga}", ""]
    lineas += [
        "\\begin{uxtablalarga}{@{}L{3.8cm} L{3.2cm} Y@{}}%",
        "{Radios, sombras, puntos de quiebre y medidas de densidad}%",
        "{\\thd{Token} & \\thd{Valor} & \\thd{Uso}}",
    ]
    for nombre, valor, uso in ESPEC_RADIOS:
        lineas.append(
            f"\\texttt{{--radius-{_texto_tex(nombre)}}} & {valor} px & "
            f"{_texto_tex(uso)} \\\\"
        )
    tinta = sistema.tono("ink-strong")
    for (nombre, desplazamiento, uso), opacidad in zip(
        ESPEC_SOMBRAS, ESPEC_OPACIDAD_SOMBRA, strict=True
    ):
        lineas.append(
            f"\\texttt{{--shadow-{_texto_tex(nombre)}}} & "
            f"\\texttt{{{_texto_tex(desplazamiento)}}} sobre "
            f"\\texttt{{{_texto_tex(tinta.nombre)}}} al "
            f"{opacidad * 100:.0f}\\% & {_texto_tex(uso)} \\\\"
        )
    for nombre, valor, uso in ESPEC_QUIEBRES:
        lineas.append(
            f"\\texttt{{--breakpoint-{_texto_tex(nombre)}}} & {valor} px & "
            f"{_texto_tex(uso)} \\\\"
        )
    for nombre, valor, uso in ESPEC_DENSIDAD:
        lineas.append(
            f"\\texttt{{--{_texto_tex(nombre)}}} & {valor} px & {_texto_tex(uso)} \\\\"
        )
    lineas += [
        "\\end{uxtablalarga}",
        "\\vspace{-6pt}{\\footnotesize\\color{uxmuted}La ret\\'icula es de doce "
        "columnas con un canal de \\texttt{--grid-gap} y m\\'argenes de "
        "\\texttt{--card-padding}. Toda medida de la interfaz es un m\\'ultiplo "
        "de 4 px: no hay valores sueltos entre pasos.\\par}%",
        "}",
        "",
    ]
    return "\n".join(lineas)


def _tono_json(tono: Tono) -> dict[str, Any]:
    """Serialise one token for the manifest."""
    return {
        "nombre": tono.nombre,
        "tono": tono.tono,
        "hex": tono.color.hex,
        "clase": tono.clase,
        "nombre_tex": tono.color.nombre_tex,
        "es_ancla": tono.es_ancla,
        "reusa": tono.reusa,
        "uso": tono.uso,
    }


def _par_json(par: ParContraste) -> dict[str, Any]:
    """Serialise one contrast pair for the manifest."""
    return {
        "frente": par.frente.nombre,
        "frente_hex": par.frente.color.hex,
        "fondo": par.fondo.nombre,
        "fondo_hex": par.fondo.color.hex,
        "ratio": par.ratio,
        "veredicto": par.veredicto,
        "regla": par.regla,
    }


def emitir_manifiesto_json(sistema: Sistema) -> str:
    """Emit the machine readable manifest read by the tests and the verifier.

    Args:
        sistema: The design system.

    Returns:
        Full content of ``docs/entregables/datos/a4_tokens.json``.
    """
    anclas = {token.color.nombre_tex for token in sistema.tokens if token.es_ancla}
    manifiesto: dict[str, Any] = {
        "version": VERSION_GUIA,
        "fecha": FECHA_GUIA,
        "fuente": "docs/entregables/estilo/uxdoc.sty",
        "generador": "docs/entregables/generar_tokens_a4.py",
        "resumen": {
            "familias": len(sistema.familias),
            "tonos_por_familia": len(TONOS_VALIDOS),
            "neutros": len(sistema.neutros),
            "semanticos": len(sistema.semanticos),
            "series": len(sistema.series),
            "tokens_de_color": len(sistema.tokens),
            "anclas": len(anclas),
            "alias_us001": len(sistema.alias),
            "pares_de_contraste": len(sistema.contrastes),
            "hallazgos": len(sistema.hallazgos),
            "roles_tipograficos": len(sistema.tipografia),
        },
        "familias": [
            {
                "clave": familia.clave,
                "etiqueta": familia.etiqueta,
                "tonos": [_tono_json(paso) for paso in familia.tonos],
            }
            for familia in sistema.familias
        ],
        "neutros": [_tono_json(tono) for tono in sistema.neutros],
        "semanticos": [_tono_json(tono) for tono in sistema.semanticos],
        "series": [_tono_json(tono) for tono in sistema.series],
        "alias_us001": [
            {
                "nombre": alias.nombre,
                "origen": alias.origen,
                "hex": alias.tono.color.hex,
            }
            for alias in sistema.alias
        ],
        "contrastes": [_par_json(par) for par in sistema.contrastes],
        "hallazgos": [
            {
                "numero": hallazgo.numero,
                "par": _par_json(hallazgo.par),
                "sustituto": _par_json(hallazgo.sustituto),
                "diagnostico": hallazgo.diagnostico,
            }
            for hallazgo in sistema.hallazgos
        ],
        "reglas_derivadas": list(REGLAS_DERIVADAS),
        "tipografia": [
            {
                "clave": rol.clave,
                "etiqueta": rol.etiqueta,
                "clase": rol.clase,
                "tamano_px": rol.tamano_px,
                "interlinea_px": rol.interlinea_px,
                "peso": rol.peso,
                "familia": rol.familia,
                "uso": rol.uso,
            }
            for rol in sistema.tipografia
        ],
        "espaciado_px": list(ESCALA_ESPACIADO),
        "radios_px": {nombre: valor for nombre, valor, _ in ESPEC_RADIOS},
        "quiebres_px": {nombre: valor for nombre, valor, _ in ESPEC_QUIEBRES},
        "densidad_px": {nombre: valor for nombre, valor, _ in ESPEC_DENSIDAD},
    }
    return json.dumps(manifiesto, ensure_ascii=False, indent=2) + "\n"


def _salidas(sistema: Sistema) -> tuple[tuple[Path, str], ...]:
    """Pair every output path with the content the system produces for it.

    Both outputs live under ``docs/entregables/``. This module owns those two
    files and no others: the ones under ``frontend/`` have a single emitter,
    ``design/emitir.py``.
    """
    return (
        (RUTA_TEX, emitir_laminas_tex(sistema)),
        (RUTA_JSON, emitir_manifiesto_json(sistema)),
    )


def _bajo(ruta: Path, destino: Path | None) -> Path:
    """Return where ``ruta`` is read or written on this run.

    Args:
        ruta: Canonical output path, always inside the repository.
        destino: Root that replaces the repository, or ``None`` to work in
            place. The relative path is kept, so a mirrored tree can be
            compared directory against directory.

    Returns:
        The path this run works on.
    """
    if destino is None:
        return ruta
    return destino / ruta.relative_to(RAIZ)


def _coincide(ruta: Path, contenido: str) -> bool:
    """Tell whether the file on disk already holds what the emitter produces.

    The comparison reads the file as text so the end of line marker does not
    decide the answer: this repository is cloned with ``core.autocrlf=true`` on
    Windows, so a freshly checked out output arrives with CRLF while the emitter
    always writes LF. Comparing bytes would report a false divergence on every
    clean clone.

    Args:
        ruta: Output path.
        contenido: Content the emitter produces today.

    Returns:
        True when the file exists and its content matches.
    """
    if not ruta.exists():
        return False
    return ruta.read_text(encoding="utf-8") == contenido


def main(argv: Sequence[str] | None = None) -> int:
    """Run the emitter.

    Args:
        argv: Command line arguments. ``None`` reads ``sys.argv``.

    Returns:
        Process exit code. With ``--verificar`` it is 1 when any output on disk
        differs from what the stylesheet produces today.
    """
    analizador = argparse.ArgumentParser(
        description=(
            "Emite la guia de estilos del informe desde uxdoc.sty: laminas "
            "LaTeX y manifiesto. Los tokens del portal salen de design/emitir.py."
        )
    )
    analizador.add_argument(
        "--verificar",
        action="store_true",
        help="recorre todo sin escribir y devuelve 1 si alguna salida difiere",
    )
    analizador.add_argument(
        "--destino",
        type=Path,
        default=None,
        metavar="DIR",
        help=(
            "escribe -o compara- bajo DIR conservando la ruta relativa, en vez "
            "de sobre el arbol de trabajo"
        ),
    )
    argumentos = analizador.parse_args(argv)

    colores = leer_definecolor(RUTA_FUENTE)
    sistema = construir_sistema(colores)
    salidas = _salidas(sistema)

    if argumentos.verificar:
        divergentes = [
            ruta
            for ruta, contenido in salidas
            if not _coincide(_bajo(ruta, argumentos.destino), contenido)
        ]
        for ruta in divergentes:
            LOG.error(
                "salida divergente",
                archivo=str(ruta.relative_to(RAIZ)),
                remedio="make tokens",
            )
        if divergentes:
            return 1
        LOG.info(
            "tokens verificados",
            colores=len(colores),
            tokens=len(sistema.tokens),
            salidas=len(salidas),
        )
        return 0

    for ruta, contenido in salidas:
        escrita = _bajo(ruta, argumentos.destino)
        escrita.parent.mkdir(parents=True, exist_ok=True)
        escrita.write_bytes(contenido.encode("utf-8"))
        LOG.info("salida emitida", archivo=str(ruta.relative_to(RAIZ)))
    LOG.info(
        "tokens emitidos",
        version=VERSION_GUIA,
        fecha=FECHA_GUIA,
        colores=len(colores),
        tokens=len(sistema.tokens),
        pares=len(sistema.contrastes),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
