"""Contract tests of the ``export_job`` migration and its Python mirror.

The suite reads SQL as text and opens no connection: PostgreSQL runs in Compose
and is not a precondition of ``make test``. What is asserted here is the pair of
seams that no other test covers, because both halves of each pair live in
different files and nothing forces them to move together: the states of
``EstadoTrabajo`` against the ``CHECK`` of the table, and the exportable
datasets of ``backend/app/models/export.py`` against the catalog sources that
declare an extract in ``db/seeds/catalog.sql``.

``tests/backend/test_migraciones.py`` already covers what every migration owes
the directory -name, both sections, unique version, presence in the dump- and
none of that is repeated here.
"""

import re
from pathlib import Path
from typing import Final

import pytest
from pydantic import BaseModel, ValidationError

from app.models.export import (
    DATASETS_EXPORTABLES,
    EstadoTrabajo,
    FormatoExportacion,
    SolicitudExportacion,
    TrabajoDetalle,
    TrabajoResumen,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS_DIR = REPO_ROOT / "db" / "migrations"
SCHEMA_FILE = REPO_ROOT / "db" / "schema.sql"
CATALOG_SEED = REPO_ROOT / "db" / "seeds" / "catalog.sql"

UP_MARKER = "-- migrate:up"
DOWN_MARKER = "-- migrate:down"

TABLE_NAME = "export_job"

# The three indexes of section 8 of the plan, by their exact names. They are
# listed once and consumed by the reversibility test and by the dump test, so a
# rename cannot pass one of the two.
INDEXES: Final[tuple[str, ...]] = (
    "export_job_requested_by_created_at_idx",
    "export_job_status_vivos_idx",
    "export_job_expires_at_idx",
)

# The two coherence constraints. They are the ones that keep the history from
# holding a state the interface cannot paint: a completed job with no file, or
# a failed job with no reason.
CONSTRAINTS: Final[tuple[str, ...]] = (
    "export_job_completado_coherente",
    "export_job_fallido_coherente",
)


def migration_path() -> Path:
    """Locate the ``create_export_job`` migration by slug, not by timestamp.

    The version is generated by ``dbmate new`` at the moment the file is
    created, so hard coding it here would make the suite depend on the clock of
    whoever ran the command.

    Returns:
        The path of the single migration whose slug is ``create_export_job``.
    """
    matches = sorted(MIGRATIONS_DIR.glob("*_create_export_job.sql"))
    assert len(matches) == 1, (
        f"Se esperaba una sola migracion create_export_job, hay {len(matches)}"
    )
    return matches[0]


def section_body(sql: str, marker: str) -> str:
    """Return the SQL that follows a dbmate section marker.

    Args:
        sql: Full content of a migration file.
        marker: Marker that opens the section.

    Returns:
        The raw text of the section, empty when the marker is absent.
    """
    lines = sql.splitlines()
    try:
        start = next(
            index for index, line in enumerate(lines) if line.strip() == marker
        )
    except StopIteration:
        return ""
    body: list[str] = []
    for line in lines[start + 1 :]:
        if line.strip() in (UP_MARKER, DOWN_MARKER):
            break
        body.append(line)
    return "\n".join(body)


def check_values(sql: str, column: str) -> set[str]:
    """Extract the literals of a ``CHECK (<column> IN (...))`` constraint.

    Args:
        sql: SQL text to scan, normally the body of the up section.
        column: Column the constraint guards.

    Returns:
        The set of quoted literals the constraint admits, empty when the column
        carries no such constraint.
    """
    pattern = re.compile(
        rf"CHECK\s*\(\s*{re.escape(column)}\s+IN\s*\(([^)]*)\)\s*\)",
        re.IGNORECASE,
    )
    match = pattern.search(sql)
    if match is None:
        return set()
    return set(re.findall(r"'([^']*)'", match.group(1)))


MIGRATION = migration_path()
MIGRATION_SQL = MIGRATION.read_text(encoding="utf-8")
UP_BODY = section_body(MIGRATION_SQL, UP_MARKER)
DOWN_BODY = section_body(MIGRATION_SQL, DOWN_MARKER)
SCHEMA_SQL = SCHEMA_FILE.read_text(encoding="utf-8")


def test_migracion_es_reversible() -> None:
    """T-13. The down section undoes the three indexes and the table.

    A down that forgets an object leaves ``dbmate rollback`` with debris the
    next ``dbmate up`` collides with, and ``db/schema.sql`` stops describing any
    reachable state of the database.
    """
    assert UP_BODY.strip(), f"{MIGRATION.name} no aplica nada en {UP_MARKER}"
    assert DOWN_BODY.strip(), (
        f"{MIGRATION.name} no revierte nada en {DOWN_MARKER}: "
        "un rollback vacio no es un rollback"
    )

    assert re.search(
        rf"DROP\s+TABLE\s+IF\s+EXISTS\s+{TABLE_NAME}", DOWN_BODY, re.IGNORECASE
    ), f"El {DOWN_MARKER} no borra la tabla {TABLE_NAME}"

    for index in INDEXES:
        assert re.search(
            rf"DROP\s+INDEX\s+IF\s+EXISTS\s+{index}", DOWN_BODY, re.IGNORECASE
        ), f"El {DOWN_MARKER} no revierte el indice {index}"


def test_estados_tienen_check() -> None:
    """T-14. The four states are enforced by SQL, not only by Python.

    Without the constraint the last line of defense is a Pydantic model, and a
    direct ``UPDATE`` -a fix by hand during the demo, a seed, a script- can park
    a job in a state the interface has no copy for and the polling store never
    leaves.
    """
    estados = check_values(UP_BODY, "status")

    assert estados == {"pendiente", "en_proceso", "completado", "fallido"}, (
        f"El CHECK de status admite {sorted(estados)}, "
        "que no son los cuatro estados del ciclo de vida"
    )
    assert "CREATE TYPE" not in UP_BODY.upper(), (
        "Los estados van con CHECK y no con un ENUM nativo: anadir un valor a "
        "un ENUM es una migracion con bloqueo"
    )


def test_estados_de_python_espejan_el_check() -> None:
    """``EstadoTrabajo`` and the SQL constraint admit the same set.

    The two halves live in different files and nothing links them: a fifth
    state added in Python would be persisted by SQLModel and rejected by the
    database at the worst possible moment, inside the background task, where the
    only trace is a job stuck in ``en_proceso``.
    """
    assert {estado.value for estado in EstadoTrabajo} == check_values(
        UP_BODY, "status"
    ), (
        "EstadoTrabajo y el CHECK de status divergieron: "
        "un estado nuevo se anade en los dos sitios o en ninguno"
    )


def test_formatos_de_python_espejan_el_check() -> None:
    """``FormatoExportacion`` and the SQL constraint admit the same set.

    Same seam as the states, and the same failure: a third format accepted by
    the request body would produce a row the database refuses to store.
    """
    assert {formato.value for formato in FormatoExportacion} == check_values(
        UP_BODY, "export_format"
    ), (
        "FormatoExportacion y el CHECK de export_format divergieron: "
        "un formato nuevo se anade en los dos sitios o en ninguno"
    )


def test_schema_incluye_export_job() -> None:
    """T-15. The versioned dump was regenerated after applying the migration.

    ``db/schema.sql`` is compared byte to byte: applying the migration without
    running ``make db-up`` leaves a dump that describes a database nobody has,
    and the next person to apply it gets a diff they did not cause.
    """
    version = MIGRATION.name[:14]

    assert f"CREATE TABLE public.{TABLE_NAME}" in SCHEMA_SQL, (
        f"db/schema.sql no declara la tabla {TABLE_NAME}: "
        "regenera el volcado con make db-up"
    )
    assert f"('{version}')" in SCHEMA_SQL, (
        f"db/schema.sql no registra la version {version} en schema_migrations"
    )

    for index in INDEXES:
        assert index in SCHEMA_SQL, f"db/schema.sql no refleja el indice {index}"

    for constraint in CONSTRAINTS:
        assert constraint in SCHEMA_SQL, (
            f"db/schema.sql no refleja el CONSTRAINT {constraint}"
        )


def test_datasets_exportables_son_los_del_catalogo_con_extracto() -> None:
    """The export whitelist equals the catalog sources that hold an extract.

    ``DATASETS_EXPORTABLES`` is a frozen constant because the validator runs
    before any session exists, and a frozen constant goes stale in silence. The
    defect this catches is a source that gains or loses its Parquet extract in
    the seed while the whitelist stays as it was: an export accepted for a
    source with no file can only end as ``fallido``, and one refused for a
    source that has one is a feature that quietly disappeared.
    """
    seed = CATALOG_SEED.read_text(encoding="utf-8")
    con_extracto = {
        match.group(1)
        for match in re.finditer(
            r"^\s*\('([a-z_]+)',.*,\s*true\)[,;]?\s*$", seed, re.MULTILINE
        )
    }

    assert con_extracto, (
        "No se hallo ninguna fuente con has_extract en db/seeds/catalog.sql: "
        "el criterio de esta prueba dejo de leer el seed"
    )
    assert set(DATASETS_EXPORTABLES) == con_extracto, (
        f"DATASETS_EXPORTABLES es {sorted(DATASETS_EXPORTABLES)} y el catalogo "
        f"declara extracto para {sorted(con_extracto)}"
    )


def test_dataset_desconocido_se_rechaza_con_pista() -> None:
    """A near miss is refused and names the source the caller probably meant.

    Two defects at once: a validator that lets any string through creates a job
    that can only fail seconds later inside the background task, and a hint with
    no similarity floor answers ``creditos`` to anything with a ``c`` in it,
    which sends the reader to the wrong dataset.
    """
    with pytest.raises(ValidationError) as cercano:
        SolicitudExportacion(dataset="credito")

    assert "el mas parecido es 'creditos'" in str(cercano.value)

    with pytest.raises(ValidationError) as lejano:
        SolicitudExportacion(dataset="nomina")

    assert "el mas parecido" not in str(lejano.value)


def test_dataset_valido_se_acepta_sin_espacios() -> None:
    """A name pasted with surrounding spaces still names its dataset.

    The value travels to ``scan_parquet`` as part of a file name: an untrimmed
    space would look for ``creditos .parquet`` and fail with a message about a
    missing file instead of about a malformed request.
    """
    solicitud = SolicitudExportacion(dataset="  creditos  ")

    assert solicitud.dataset == "creditos"
    assert solicitud.formato is FormatoExportacion.CSV
    assert solicitud.filtros == {}


@pytest.mark.parametrize(
    ("estado", "terminal"),
    [
        (EstadoTrabajo.PENDIENTE, False),
        (EstadoTrabajo.EN_PROCESO, False),
        (EstadoTrabajo.COMPLETADO, True),
        (EstadoTrabajo.FALLIDO, True),
    ],
)
def test_solo_completado_y_fallido_son_terminales(
    estado: EstadoTrabajo, terminal: bool
) -> None:
    """The polling store stops on exactly two states.

    Marking ``en_proceso`` terminal freezes the interface on a job that is still
    running; leaving ``fallido`` out of the terminal set leaves the timer
    polling a row that will never change again until the cap of 200 polls.

    Args:
        estado: State under inspection.
        terminal: Whether the job will not change state again.
    """
    assert estado.es_terminal is terminal


@pytest.mark.parametrize("contrato", [TrabajoResumen, TrabajoDetalle])
def test_los_contratos_no_publican_object_key(contrato: type[BaseModel]) -> None:
    """No response contract carries the storage handle of the file.

    The column comment states it in SQL -"jamas se serializa en una
    respuesta"- and nothing enforces it: adding ``object_key`` to a contract is
    one line and it would hand every caller the internal name of an object in
    the bucket, which is a name worth guessing against.

    Args:
        contrato: Response contract under inspection.
    """
    assert "object_key" not in contrato.model_fields, (
        f"{contrato.__name__} publica object_key, que es interno del almacen"
    )
